import { useRef, useState } from 'react';
import { BarChart3, Camera, FileText, Globe2, Loader2, MoreHorizontal, Music2, Video, X } from 'lucide-react';
import { useAuth } from '../../../hooks/useAuth';

export function PostComposer({ isLoading, onSubmit }: { isLoading:boolean; onSubmit:(content:string,type:string,photos:File[])=>void }) {
  const {user}=useAuth(); const [content,setContent]=useState(''); const [photos,setPhotos]=useState<File[]>([]); const inputRef=useRef<HTMLInputElement>(null);
  const name=user?.user_metadata?.full_name?.split(' ')[0]||'Usuario'; const avatar=user?.user_metadata?.avatar_url||`https://ui-avatars.com/api/?name=${encodeURIComponent(user?.user_metadata?.full_name||'User')}`;
  const submit=()=>{const text=content.trim();if(!text&&!photos.length)return;onSubmit(text,photos.length?'photo':'text',photos);setContent('');setPhotos([]);if(inputRef.current)inputRef.current.value='';};
  const addPhotos=(files:FileList|null)=>{if(!files)return;const images=Array.from(files).filter(f=>f.type.startsWith('image/')).slice(0,4-photos.length);if(images.length)setPhotos(p=>[...p,...images]);};
  return <section style={{background:'#fff',border:'1px solid #d9e1e8',boxShadow:'0 1px 2px rgba(0,0,0,.04)'}}>
    <div style={{display:'flex',gap:14,padding:18}}><img src={avatar} alt="" style={{width:48,height:48,borderRadius:'50%',objectFit:'cover'}}/><textarea value={content} onChange={e=>setContent(e.target.value)} rows={2} placeholder={`¿Qué estás pensando, ${name}?`} style={{flex:1,minHeight:58,resize:'none',border:'1px solid #cfd8e2',padding:'12px 15px',fontSize:16,outline:'none',fontFamily:'inherit'}}/></div>
    {photos.length>0&&<div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:5,padding:'0 18px 14px'}}>{photos.map((p,i)=><div key={`${p.name}-${i}`} style={{position:'relative',aspectRatio:'1',overflow:'hidden'}}><img src={URL.createObjectURL(p)} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/><button type="button" onClick={()=>setPhotos(c=>c.filter((_,x)=>x!==i))} style={{position:'absolute',right:5,top:5,border:0,borderRadius:'50%',background:'rgba(0,0,0,.7)',color:'#fff',padding:5}}><X size={14}/></button></div>)}</div>}
    <input ref={inputRef} type="file" accept="image/*" multiple style={{display:'none'}} onChange={e=>addPhotos(e.target.files)}/>
    <div style={{display:'flex',borderTop:'1px solid #edf0f3',borderBottom:'1px solid #edf0f3',padding:'0 8px'}}>{[[<FileText size={18}/>,'Estado'],[<Camera size={18}/>,'Foto'],[<Video size={18}/>,'Vídeo'],[<Music2 size={18}/>,'Música'],[<BarChart3 size={18}/>,'Encuesta'],[<FileText size={18}/>,'Noticia'],[<MoreHorizontal size={18}/>,'Más']].map(([icon,label],i)=><button key={String(label)} type="button" onClick={i===1?()=>inputRef.current?.click():undefined} style={{display:'flex',alignItems:'center',gap:7,border:0,background:'#fff',padding:'13px 11px',color:'#45566b',fontSize:13,fontWeight:600}}>{icon}{label}</button>)}</div>
    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'12px 18px'}}><button type="button" style={{border:0,background:'#fff',display:'flex',alignItems:'center',gap:6,color:'#667484',fontSize:13}}><Globe2 size={17}/>Público <MoreHorizontal size={14}/></button><button type="button" onClick={submit} disabled={isLoading||(!content.trim()&&!photos.length)} style={{minWidth:112,border:0,background:'#4b86d7',color:'#fff',padding:'10px 24px',fontSize:14,fontWeight:800,opacity:isLoading||(!content.trim()&&!photos.length)?0.5:1}}>{isLoading?<Loader2 size={18} style={{margin:'auto'}}/>:'Publicar'}</button></div>
  </section>;
}
