import { supabase } from '../../lib/supabase';
import { usePlayerStore } from '../../lib/store';

 type Track = { id:string; title:string; artist:string|null; cover_url:string|null; youtube_id:string|null; source_type:string; album:string|null; user_id:string|null };
 type Playlist = { id:string; name:string; description:string|null; is_public?:boolean };
 const esc=(v:unknown)=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]||c));
 const cover=(t?:Track|null)=>t?.cover_url||(t?.youtube_id?`https://i.ytimg.com/vi/${t.youtube_id}/hqdefault.jpg`:'');
 const player=()=>usePlayerStore.getState();
 const localDay=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};

 async function context(){
   const page=document.querySelector<HTMLElement>('.profile-view-page'); if(!page) return null;
   const session=await supabase.auth.getSession(); const ownId=session.data.session?.user?.id||'';
   const handle=page.querySelector('.profile-view-handle')?.textContent?.trim().replace(/^@/,'')||'';
   if(!handle)return {page,id:ownId,own:true};
   const {data}=await supabase.from('profiles').select('id').eq('username',handle).maybeSingle();
   return {page,id:data?.id||ownId,own:data?.id===ownId};
 }
 const modal=(title:string,body:string)=>{document.querySelector('.profile-music-functional-backdrop')?.remove();const h=document.createElement('div');h.className='profile-music-functional-backdrop';h.innerHTML=`<div class="profile-music-functional-modal"><div class="profile-music-functional-head"><h3>${esc(title)}</h3><button type="button" data-functional-close>×</button></div><div class="profile-music-functional-body">${body}</div></div>`;document.body.appendChild(h);h.addEventListener('click',e=>{const t=e.target as HTMLElement;if(t===h||t.closest('[data-functional-close]'))h.remove()});return h};
 const play=(t:Track|null)=>{if(!t)return;player().playSong({type:t.source_type==='youtube'?'youtube_song':'local_song',video_id:t.youtube_id||undefined,title:t.title,artist:t.artist||undefined,channel_title:t.artist||undefined,thumbnail:cover(t)} as any,false)};
 async function getTrack(id:string){const {data}=await supabase.from('music_tracks').select('id,title,artist,cover_url,youtube_id,source_type,album,user_id').eq('id',id).maybeSingle();return data as Track|null}
 async function refresh(){document.querySelectorAll<HTMLButtonElement>('.profile-view-tabs button').forEach(b=>{if(b.textContent?.trim()==='Música')b.click()})}

 async function daily(ctx:any){
   if(!ctx?.own)return;
   const {data:tracks}=await supabase.from('music_tracks').select('id,title,artist,cover_url,youtube_id,source_type,album,user_id').eq('user_id',ctx.id).order('created_at',{ascending:false}).limit(100);
   const {data:current}=await supabase.from('profile_song_of_day').select('track_id').eq('user_id',ctx.id).maybeSingle();
   const list=((tracks||[]) as Track[]).map(t=>`<div class="functional-row"><img src="${esc(cover(t))}"><div><strong>${esc(t.title)}</strong><small>${esc(t.artist||'')}</small></div><button class="functional-primary" data-func-day="${t.id}">${current?.track_id===t.id?'Elegida ✓':'Elegir'}</button></div>`).join('');
   const h=modal('Elegir canción del día',`<p class="functional-help">Una canción por día. Se sincroniza con el perfil y el Diario musical.</p><div class="functional-list">${list||'<div class="functional-empty">Añade música primero.</div>'}</div>`);
   h.querySelector('.functional-list')?.addEventListener('click',async e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-func-day]');if(!b)return;try{const id=b.dataset.funcDay!;const now=new Date().toISOString();const a=await supabase.from('profile_song_of_day').upsert({user_id:ctx.id,track_id:id,updated_at:now},{onConflict:'user_id'});if(a.error)throw a.error;const d=await supabase.from('profile_music_diary').upsert({user_id:ctx.id,entry_date:localDay(),track_id:id},{onConflict:'user_id,entry_date'});if(d.error)throw d.error;window.dispatchEvent(new CustomEvent('inkorium:daily-song-changed'));h.remove();await refresh()}catch(err:any){alert(err?.message||'No se pudo guardar la canción del día.')}})
 }

 async function playlistEdit(ctx:any,id?:string){if(!ctx?.own)return;let p:Playlist|undefined;if(id){const {data}=await supabase.from('music_playlists').select('id,name,description,is_public').eq('id',id).maybeSingle();p=data as Playlist|null||undefined}const h=modal(p?'Editar playlist':'Nueva playlist',`<label>Nombre<input id="fplName" value="${esc(p?.name||'')}"></label><label>Descripción<textarea id="fplDesc" rows="3">${esc(p?.description||'')}</textarea></label><label class="functional-check"><input id="fplPublic" type="checkbox" ${p?.is_public!==false?'checked':''}> Playlist pública</label><div class="functional-actions"><button type="button" data-functional-close>Cancelar</button><button type="button" class="functional-primary" id="fplSave">${p?'Guardar cambios':'Crear playlist'}</button></div>`);h.querySelector('#fplSave')?.addEventListener('click',async()=>{const name=h.querySelector<HTMLInputElement>('#fplName')!.value.trim();if(!name){alert('Ponle un nombre a la playlist.');return}const description=h.querySelector<HTMLTextAreaElement>('#fplDesc')!.value.trim();const isPublic=h.querySelector<HTMLInputElement>('#fplPublic')!.checked;const result=p?await supabase.from('music_playlists').update({name,description:description||null,is_public:isPublic}).eq('id',p.id).eq('user_id',ctx.id):await supabase.from('music_playlists').insert({user_id:ctx.id,name,description:description||null,is_public:isPublic});if(result.error)alert(result.error.message);else{h.remove();await refresh()}})}
 async function playlistSongs(ctx:any,id:string){if(!ctx?.own)return;const {data}=await supabase.from('music_tracks').select('id,title,artist,cover_url,youtube_id,source_type,album,user_id').eq('user_id',ctx.id).order('created_at',{ascending:false}).limit(100);const h=modal('Añadir canciones a la playlist',`<p class="functional-help">Selecciona canciones guardadas.</p><div class="functional-list">${((data||[]) as Track[]).map(t=>`<div class="functional-row"><img src="${esc(cover(t))}"><div><strong>${esc(t.title)}</strong><small>${esc(t.artist||'')}</small></div><button type="button" class="functional-primary" data-fplTrack="${t.id}">Añadir</button></div>`).join('')||'<div class="functional-empty">No tienes canciones guardadas.</div>'}</div>`);h.querySelector('.functional-list')?.addEventListener('click',async e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-fpltrack]');if(!b)return;const {data:last}=await supabase.from('music_playlist_items').select('position').eq('playlist_id',id).order('position',{ascending:false}).limit(1).maybeSingle();const pos=Number(last?.position||0)+1;const {error}=await supabase.from('music_playlist_items').upsert({playlist_id:id,track_id:b.dataset.fpltrack!,position:pos},{onConflict:'playlist_id,track_id'});if(error)alert(error.message);else b.textContent='Añadida ✓'})}
 async function playlistDelete(ctx:any,id:string){if(!ctx?.own)return;if(!confirm('¿Eliminar esta playlist?'))return;const {error}=await supabase.from('music_playlists').delete().eq('id',id).eq('user_id',ctx.id);if(error)alert(error.message);else await refresh()}

 async function editTrack(ctx:any,id:string){if(!ctx?.own)return;const t=await getTrack(id);if(!t)return;const h=modal('Editar canción',`<label>Título<input id="fetTitle" value="${esc(t.title)}"></label><label>Artista<input id="fetArtist" value="${esc(t.artist||'')}"></label><label>Álbum<input id="fetAlbum" value="${esc(t.album||'')}"></label><div class="functional-actions"><button type="button" data-functional-close>Cancelar</button><button type="button" class="functional-primary" id="fetSave">Guardar cambios</button></div>`);h.querySelector('#fetSave')?.addEventListener('click',async()=>{const title=h.querySelector<HTMLInputElement>('#fetTitle')!.value.trim(),artist=h.querySelector<HTMLInputElement>('#fetArtist')!.value.trim(),album=h.querySelector<HTMLInputElement>('#fetAlbum')!.value.trim();if(!title){alert('El título es obligatorio.');return}const {error}=await supabase.from('music_tracks').update({title,artist:artist||null,album:album||null}).eq('id',id).eq('user_id',ctx.id);if(error)alert(error.message);else{h.remove();await refresh()}})}
 async function albums(ctx:any){if(!ctx?.own)return;const {data}=await supabase.from('music_tracks').select('id,title,artist,cover_url,youtube_id,source_type,album,user_id').eq('user_id',ctx.id).order('created_at',{ascending:false}).limit(100);const h=modal('Álbumes destacados',`<p class="functional-help">Edita el álbum de cualquier canción. Las canciones con álbum aparecen aquí.</p><div class="functional-list">${((data||[]) as Track[]).map(t=>`<div class="functional-row"><img src="${esc(cover(t))}"><div><strong>${esc(t.title)}</strong><small>${esc(t.artist||'')}${t.album?' · '+esc(t.album):' · Sin álbum'}</small></div><button type="button" class="functional-primary" data-falbum="${t.id}">Editar</button></div>`).join('')}</div>`);h.querySelector('.functional-list')?.addEventListener('click',async e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-falbum]');if(!b)return;h.remove();await editTrack(ctx,b.dataset.falbum!)})}
 async function taste(ctx:any){if(!ctx?.own)return;const {data:tracks}=await supabase.from('music_tracks').select('id,title,artist,cover_url,youtube_id,source_type,album,user_id').eq('user_id',ctx.id).limit(100);const {data:favs}=await supabase.from('music_favorites').select('track_id').eq('user_id',ctx.id).limit(200);const ids=new Set((favs||[]).map((r:any)=>r.track_id));const artists=new Map<string,Track[]>();((tracks||[]) as Track[]).forEach(t=>{if(!t.artist)return;const a=artists.get(t.artist)||[];a.push(t);artists.set(t.artist,a)});const h=modal('Editar gusto musical',`<p class="functional-help">Los gustos se construyen a partir de tus canciones favoritas. Marca los artistas que quieres destacar.</p><div class="functional-list">${Array.from(artists.entries()).sort().map(([artist,songs])=>{const on=songs.some(s=>ids.has(s.id));const rep=songs[0];return `<label class="functional-artist-option"><input type="checkbox" data-fartist="${esc(artist)}" ${on?'checked':''}><img src="${esc(cover(rep))}"><span>${esc(artist)}</span></label>`}).join('')||'<div class="functional-empty">Añade música primero.</div>'}</div>`);h.querySelector('.functional-list')?.addEventListener('change',async e=>{const i=(e.target as HTMLInputElement).closest<HTMLInputElement>('[data-fartist]');if(!i)return;const artist=i.dataset.fartist!,songs=artists.get(artist)||[];try{if(i.checked){const song=songs[0];const r=await supabase.from('music_favorites').upsert({user_id:ctx.id,track_id:song.id},{onConflict:'user_id,track_id'});if(r.error)throw r.error}else{const r=await supabase.from('music_favorites').delete().eq('user_id',ctx.id).in('track_id',songs.map(s=>s.id));if(r.error)throw r.error}window.dispatchEvent(new CustomEvent('inkorium:music-data-changed'))}catch(err:any){i.checked=!i.checked;alert(err?.message||'No se pudo actualizar')}})}

 function profileSection(target:HTMLElement){return target.closest('section')?.querySelector('h2')?.textContent?.trim()||''}
 async function handler(e:MouseEvent){const t=e.target as HTMLElement;const root=document.querySelector<HTMLElement>('.profile-view-page');if(!root)return;const ctx=await context();if(!ctx?.own)return;
   const day=t.closest<HTMLElement>('[data-music-action="day"]');if(day){e.preventDefault();e.stopImmediatePropagation();await daily(ctx);return}
   const section=profileSection(t);
   const generic=t.closest<HTMLElement>('[data-music-action="add"]');if(generic&&section.includes('Álbumes destacados')){e.preventDefault();e.stopImmediatePropagation();await albums(ctx);return}
   const tasteButton=t.closest<HTMLElement>('.profile-music-side-card [data-music-action="add"]');if(tasteButton){e.preventDefault();e.stopImmediatePropagation();await taste(ctx);return}
   const plNew=t.closest<HTMLElement>('[data-music-action="new-playlist"]');if(plNew){e.preventDefault();e.stopImmediatePropagation();await playlistEdit(ctx);return}
   const plEdit=t.closest<HTMLElement>('[data-edit-playlist]');if(plEdit){e.preventDefault();e.stopImmediatePropagation();await playlistEdit(ctx,plEdit.dataset.editPlaylist);return}
   const plAdd=t.closest<HTMLElement>('[data-playlist-add]');if(plAdd){e.preventDefault();e.stopImmediatePropagation();await playlistSongs(ctx,plAdd.dataset.playlistAdd!);return}
   const plDel=t.closest<HTMLElement>('[data-delete-playlist]');if(plDel){e.preventDefault();e.stopImmediatePropagation();await playlistDelete(ctx,plDel.dataset.deletePlaylist!);return}
   const edit=t.closest<HTMLElement>('[data-edit-track]');if(edit){e.preventDefault();e.stopImmediatePropagation();await editTrack(ctx,edit.dataset.editTrack!);return}
   const playId=t.closest<HTMLElement>('[data-track-id]')?.dataset.trackId; if(playId){e.preventDefault();e.stopImmediatePropagation();play(await getTrack(playId));return}
   const fav=t.closest<HTMLElement>('[data-favorite-id]')?.dataset.favoriteId;if(fav){e.preventDefault();e.stopImmediatePropagation();const {data}=await supabase.from('music_favorites').select('track_id').eq('user_id',ctx.id).eq('track_id',fav).maybeSingle();if(data)await supabase.from('music_favorites').delete().eq('user_id',ctx.id).eq('track_id',fav);else await supabase.from('music_favorites').upsert({user_id:ctx.id,track_id:fav},{onConflict:'user_id,track_id'});await refresh();return}
 }
 function boot(){document.addEventListener('click',e=>{void handler(e as MouseEvent)},true);window.addEventListener('inkorium:music-data-changed',()=>{window.setTimeout(()=>void refresh(),50)})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
