ALTER TABLE profiles ADD COLUMN current_song_id text;
ALTER TABLE profiles ADD COLUMN current_song_title text;
ALTER TABLE profiles ADD COLUMN current_song_artist text;
ALTER TABLE profiles ADD COLUMN current_song_album text;
ALTER TABLE profiles ADD COLUMN current_song_cover text;
ALTER TABLE profiles ADD COLUMN current_song_duration text;
ALTER TABLE profiles ADD COLUMN current_song_year text;
ALTER TABLE profiles ADD COLUMN current_song_is_playing boolean;
ALTER TABLE profiles ADD COLUMN current_song_progress text;
ALTER TABLE profiles ADD COLUMN current_song_provider text;
ALTER TABLE profiles ADD COLUMN current_song_updated_at timestamp with time zone;
