import React, { useState, useEffect, useRef } from 'react';
import { createPortal } from "react-dom";
import { supabase } from '../lib/supabase';
import { Session } from '@supabase/supabase-js';
import { Image as ImageIcon, Video, Music, BarChart3, List, Search, X, ChevronDown, Globe, Users, Lock, ChevronUp, Loader2, AtSign } from 'lucide-react';
import { ProfileData } from '../main';
import { getDisplayName } from '../utils';
import { createR2UploadTicket, uploadToPresignedUrl } from '../lib/r2';

type Post = any;
type GalleryPhoto = { id: string; url: string; caption?: string | null };

function ComposerMenuPortal({ isOpen, onClose, triggerRef, onSelect }: { isOpen: boolean; onClose: () => void; triggerRef: React.RefObject<HTMLElement | null>; onSelect: (action: string) => void }) {
  const [position, setPosition] = useState({ top: 0, left: 0 });
  const menuRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (isOpen && triggerRef.current) { const rect = triggerRef.current.getBoundingClientRect(); setPosition({ top: rect.bottom + window.scrollY, left: rect.left + window.scrollX }); } }, [isOpen, triggerRef]);
  useEffect(() => { const outside=(e:MouseEvent)=>{if(menuRef.current&&!menuRef.current.contains(e.target as Node)&&triggerRef.current&&!triggerRef.current.contains(e.target as Node))onClose()}; const close=()=>onClose(); if(isOpen){document.addEventListener('mousedown',outside);window.addEventListener('scroll',close,true);window.addEventListener('resize',close)} return()=>{document.removeEventListener('mousedown',outside);window.removeEventListener('scroll',close,true);window.removeEventListener('resize',close)}} ,[isOpen,onClose,triggerRef]);
  if (!isOpen) return null;
  return createPortal(<div ref={menuRef} className="composer-more-menu" style={{position:'absolute',top:`${position.top}px`,left:`${position.left}px`,zIndex:9999}}>
    <button type="button" onClick={()=>onSelect('poll')}>❓ Pregunta</button><button type="button" onClick={()=>onSelect('news')}>🔗 Enlace</button><button type="button" onClick={()=>onSelect('background')}>🎨 Fondo / estilo</button><button type="button" onClick={()=>onSelect('mention')}>👥 Mencionar personas</button>
  </div>,document.body);
}

export function Composer({ session, profile, onPublish, targetProfileId, targetName }: { session: Session; profile: ProfileData | null; onPublish: (post: Post) => void; targetProfileId?: string; targetName?: string }) {
  const [draft,setDraft]=useState(''); const [publishing,setPublishing]=useState(false); const [error,setError]=useState(''); const [uploadProgress,setUploadProgress]=useState<number|null>(null);
  const [mode,setMode]=useState<'text'|'photo'|'video'|'music'|'poll'|'news'|'background'|'mention'>('text'); const [moreMenuOpen,setMoreMenuOpen]=useState(false);
  const [privacy,setPrivacy]=useState<'public'|'friends'|'private'>('public'); const [privacyMenuOpen,setPrivacyMenuOpen]=useState(false); const [privateUsers]=useState<ProfileData[]>([]); const [showPrivateSelector,setShowPrivateSelector]=useState(false);
  const [photoFile,setPhotoFile]=useState<File|null>(null); const [photoPreview,setPhotoPreview]=useState<string|null>(null); const [galleryPhoto,setGalleryPhoto]=useState<GalleryPhoto|null>(null); const [galleryOpen,setGalleryOpen]=useState(false); const [galleryLoading,setGalleryLoading]=useState(false); const [galleryPhotos,setGalleryPhotos]=useState<GalleryPhoto[]>([]);
  const [videoFile,setVideoFile]=useState<File|null>(null); const [videoPreview,setVideoPreview]=useState<string|null>(null);
  const [youtubeSearch,setYoutubeSearch]=useState(''); const [youtubeResults,setYoutubeResults]=useState<any[]>([]); const [youtubeSearching,setYoutubeSearching]=useState(false); const [youtubeSelected,setYoutubeSelected]=useState<any|null>(null); const [youtubeHasKey]=useState(!!import.meta.env.VITE_YOUTUBE_API_KEY);
  const [pollOptions,setPollOptions]=useState<string[]>(['','']); const [newsUrl,setNewsUrl]=useState(''); const [newsTitle,setNewsTitle]=useState(''); const [bgChoice,setBgChoice]=useState('note');
  const [mentionPickerOpen,setMentionPickerOpen]=useState(false); const [mentionQuery,setMentionQuery]=useState(''); const [mentionResults,setMentionResults]=useState<any[]>([]); const [mentionSearching,setMentionSearching]=useState(false);
  const textareaRef=useRef<HTMLTextAreaElement|null>(null); const photoInputRef=useRef<HTMLInputElement|null>(null); const mentionPickerRef=useRef<HTMLDivElement>(null); const moreMenuRef=useRef<HTMLButtonElement>(null); const privacyMenuRef=useRef<HTMLDivElement>(null);
  const username=getDisplayName(profile,session.user.email); const initials=username.slice(0,2).toUpperCase(); const avatarUrl=profile?.avatar_url; const isOwnProfile=!targetProfileId||targetProfileId===session.user.id; const placeholderText=targetProfileId&&!isOwnProfile&&targetName?`¿Qué estás pensando, ${targetName}?`:`¿Qué estás pensando, ${username}?`; const buttonText=targetProfileId&&!isOwnProfile?'Firmar':'Publicar';

  useEffect(()=>{const handler=(e:any)=>{const v=e.detail;setMode('music');setYoutubeSelected({id:{videoId:v.youtube_id},snippet:{title:v.title,channelTitle:v.channel,thumbnails:{high:{url:v.thumbnail},default:{url:v.thumbnail}}}})};window.addEventListener('open-composer-video',handler);return()=>window.removeEventListener('open-composer-video',handler)},[]);
  useEffect(()=>{const outside=(e:MouseEvent)=>{if(moreMenuRef.current&&!moreMenuRef.current.contains(e.target as Node))setMoreMenuOpen(false);if(privacyMenuRef.current&&!privacyMenuRef.current.contains(e.target as Node))setPrivacyMenuOpen(false);if(mentionPickerRef.current&&!mentionPickerRef.current.contains(e.target as Node))setMentionPickerOpen(false)};document.addEventListener('mousedown',outside);return()=>document.removeEventListener('mousedown',outside)},[]);
  useEffect(()=>{if(!mentionPickerOpen){setMentionResults([]);return}const term=mentionQuery.trim();if(!term){setMentionResults([]);return}let cancelled=false;setMentionSearching(true);const timer=window.setTimeout(async()=>{const{data}=await supabase.from('profiles').select('id, username, full_name, avatar_url').ilike('username',`%${term}%`).neq('id',session.user.id).limit(6);if(!cancelled){setMentionResults(data||[]);setMentionSearching(false)}},250);return()=>{cancelled=true;window.clearTimeout(timer)}},[mentionQuery,mentionPickerOpen,session.user.id]);
  useEffect(()=>{if(!galleryOpen)return;let cancelled=false;setGalleryLoading(true);void supabase.from('photos').select('id, url, caption').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(80).then(({data,error})=>{if(cancelled)return;setGalleryPhotos(error?[]:((data||[]) as GalleryPhoto[]));setGalleryLoading(false)});return()=>{cancelled=true}},[galleryOpen,session.user.id]);

  function insertMention(user:any){const handle=`@${user.username||getDisplayName(user,'')} `;const ta=textareaRef.current;if(ta){const start=ta.selectionStart??draft.length;const end=ta.selectionEnd??draft.length;setDraft(draft.slice(0,start)+handle+draft.slice(end));requestAnimationFrame(()=>{ta.focus();const pos=start+handle.length;ta.setSelectionRange(pos,pos)})}else setDraft(draft+handle);setMentionPickerOpen(false);setMentionQuery('')}
  function handleInput(e:React.ChangeEvent<HTMLTextAreaElement>){setDraft(e.target.value);e.target.style.height='auto';e.target.style.height=`${e.target.scrollHeight}px`}
  const handlePhotoSelect=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){setError('Selecciona una imagen válida.');return}setGalleryPhoto(null);setPhotoFile(file);setPhotoPreview(URL.createObjectURL(file));setError('')};
  const handleVideoSelect=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('video/')){setError('Selecciona un vídeo válido.');return}if(file.size>1024*1024*1024){setError('El vídeo es demasiado grande. Máximo 1GB.');return}setVideoFile(file);setVideoPreview(URL.createObjectURL(file));setError('')};
  function chooseGalleryPhoto(photo:GalleryPhoto){setGalleryPhoto(photo);setPhotoFile(null);setPhotoPreview(photo.url);setGalleryOpen(false);setError('')}
  async function searchYoutube(e:React.FormEvent){e.preventDefault();if(!youtubeSearch.trim()||!youtubeHasKey)return;setYoutubeSearching(true);setError('');try{const res=await fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&q=${encodeURIComponent(youtubeSearch)}&type=video&maxResults=10&key=${import.meta.env.VITE_YOUTUBE_API_KEY}`);const data=await res.json();if(!res.ok)throw new Error(data?.error?.message||'Error en la API de YouTube');setYoutubeResults(data.items||[])}catch(err:any){setError(err?.message||'No se pudo buscar música');setYoutubeResults([])}finally{setYoutubeSearching(false)}}
  async function publish(e:React.FormEvent){e.preventDefault();const contentText=draft.trim();if((!contentText&&mode==='text')||publishing)return;setPublishing(true);setError('');let media_data:any=null;let poll_id:string|undefined;
    try{
      if(mode==='photo'&&(photoFile||galleryPhoto)){if(photoFile){if(photoFile.size>60*1024*1024)throw new Error('La foto supera el límite de 60MB.');const ticket=await createR2UploadTicket({folder:'post-media',file:photoFile});await uploadToPresignedUrl(ticket.uploadUrl,photoFile,photoFile.type);if(!ticket.url)throw new Error('R2_PUBLIC_BASE_URL no está configurado.');media_data={type:'photo',url:ticket.url,storage_path:ticket.key,storage_backend:'r2'};}else if(galleryPhoto){media_data={type:'photo',url:galleryPhoto.url,storage_backend:'r2',reused_from_gallery:true,source_photo_id:galleryPhoto.id};}
      } else if(mode==='video'&&videoFile){const ticket=await createR2UploadTicket({folder:'post-media',file:videoFile});setUploadProgress(0);await uploadToPresignedUrl(ticket.uploadUrl,videoFile,videoFile.type);setUploadProgress(100);if(!ticket.url)throw new Error('R2_PUBLIC_BASE_URL no está configurado.');media_data={type:'video',url:ticket.url,storage_path:ticket.key,storage_backend:'r2'};const{error:dbError}=await supabase.from('user_videos').insert({user_id:session.user.id,title:contentText||videoFile.name,url:ticket.url,source:'upload'});if(dbError)throw dbError;
      } else if(mode==='music'&&youtubeSelected){media_data={type:'youtube_song',youtube_id:youtubeSelected.id.videoId,title:youtubeSelected.snippet.title,thumbnail:youtubeSelected.snippet.thumbnails?.high?.url||youtubeSelected.snippet.thumbnails?.default?.url};
      } else if(mode==='news'&&newsUrl){media_data={type:'news',url:newsUrl,title:newsTitle};
      } else if(mode==='background'){if(!contentText)throw new Error('Escribe algo de texto para la nota.');media_data={type:'background',style:bgChoice};
      } else if(mode==='poll'){const validOptions=pollOptions.filter(o=>o.trim());if(validOptions.length<2)throw new Error('Una encuesta necesita al menos 2 opciones.');if(!contentText)throw new Error('Debes escribir una pregunta.');const{data:pollData,error:pollError}=await supabase.from('polls').insert({question:contentText,author_id:session.user.id}).select('id').single();if(pollError)throw pollError;poll_id=pollData.id;const{error:optionError}=await supabase.from('poll_options').insert(validOptions.map((text,i)=>({poll_id:pollData.id,text:text.trim(),order_index:i})));if(optionError)throw optionError;
      }
      const{data,error:submitError}=await supabase.from('posts').insert({author_id:session.user.id,content:contentText,visibility:privacy,target_profile_id:targetProfileId||null,media_data,poll_id}).select('id, content, created_at, media_data, poll_id, visibility').single();if(submitError)throw submitError;
      if(data){onPublish({id:data.id,text:data.content??contentText,time:'ahora',likes:0,authorName:username,author_id:session.user.id,authorAvatarUrl:avatarUrl,commentsCount:0,media_data:data.media_data,poll_id:data.poll_id});setDraft('');setMode('text');setPhotoFile(null);setPhotoPreview(null);setGalleryPhoto(null);setVideoFile(null);setVideoPreview(null);setYoutubeSelected(null);setPollOptions(['','']);setNewsUrl('');setNewsTitle('');setUploadProgress(null);const ta=document.querySelector('.composer-input') as HTMLTextAreaElement|null;if(ta)ta.style.height='auto'}
    }catch(err:any){console.error('[COMPOSER_R2]',err);setError(err?.message||'No se pudo publicar')}finally{setUploadProgress(null);setPublishing(false)}
  }
  const renderPrivacy=()=>{const icon=privacy==='public'?<Globe size={16}/>:privacy==='friends'?<Users size={16}/>:<Lock size={16}/>;const label=privacy==='public'?'Público':privacy==='friends'?'Amigos':'Privado';return <div className="new-composer-privacy" ref={privacyMenuRef}><div className="privacy-trigger" onClick={()=>setPrivacyMenuOpen(v=>!v)}>{icon}{label}{privacyMenuOpen?<ChevronUp size={14}/>:<ChevronDown size={14}/>}</div>{privacyMenuOpen&&<div className="privacy-dropdown"><button type="button" onClick={()=>{setPrivacy('public');setPrivacyMenuOpen(false);setShowPrivateSelector(false)}}><Globe size={16}/>Público</button><button type="button" onClick={()=>{setPrivacy('friends');setPrivacyMenuOpen(false);setShowPrivateSelector(false)}}><Users size={16}/>Amigos</button><button type="button" onClick={()=>{setPrivacy('private');setPrivacyMenuOpen(false);setShowPrivateSelector(true)}}><Lock size={16}/>Privado</button></div>}</div>}
  const handleModeChange=(next:typeof mode)=>{setMode(next);setMoreMenuOpen(false);if(next==='photo'){setError('');setGalleryPhoto(null);setPhotoFile(null);setPhotoPreview(null)}if(next==='mention')setMentionPickerOpen(true)};
  return <section className="composer-container panel"><div className="composer-top"><div className="composer-avatar">{avatarUrl?<img src={avatarUrl} alt={username}/>:<div className="initials">{initials}</div>}</div><textarea ref={textareaRef} className="composer-input" value={draft} onChange={handleInput} placeholder={mode==='poll'?'Haz una pregunta...':placeholderText} rows={1}/></div>
    {mentionPickerOpen&&<div className="mention-picker" ref={mentionPickerRef}><div className="mention-picker-search"><AtSign size={14}/><input autoFocus value={mentionQuery} onChange={e=>setMentionQuery(e.target.value)} placeholder="Buscar personas..."/></div>{mentionSearching&&<div>Buscando...</div>}{mentionResults.map(u=><button type="button" key={u.id} className="mention-picker-item" onClick={()=>insertMention(u)}><span>{getDisplayName(u,'')}</span></button>)}</div>}
    {mode==='photo'&&<div className="composer-extended photo-mode">{photoPreview?<div className="composer-photo-preview"><img src={photoPreview} alt="Vista previa" style={{width:'100%',maxHeight:350,objectFit:'contain'}}/><button type="button" onClick={()=>{setPhotoFile(null);setPhotoPreview(null);setGalleryPhoto(null)}}><X size={18}/></button></div>:<div className="file-upload-box"><input ref={photoInputRef} type="file" id="photo-upload" accept="image/*" onChange={handlePhotoSelect} style={{display:'none'}}/><button type="button" className="file-upload-trigger" onClick={()=>photoInputRef.current?.click()}><ImageIcon size={24}/><span>Seleccionar imagen</span></button><button type="button" className="file-gallery-trigger" onClick={()=>setGalleryOpen(true)}>▦ <span>Elegir de mi galería</span></button></div>}</div>}
    {mode==='video'&&<div className="composer-extended video-mode">{videoPreview?<div className="composer-video-preview"><video src={videoPreview} controls style={{width:'100%',maxHeight:350}}/><button type="button" onClick={()=>{setVideoFile(null);setVideoPreview(null)}}><X size={18}/></button></div>:<div className="file-upload-box"><input type="file" id="video-upload" accept="video/*" onChange={handleVideoSelect}/><label htmlFor="video-upload"><Video size={24}/><span>Seleccionar vídeo</span></label></div>}{uploadProgress!==null&&<div>Subiendo: {uploadProgress}%</div>}</div>}
    {mode==='music'&&<div className="composer-extended music-mode"><form onSubmit={searchYoutube} className="youtube-search"><input value={youtubeSearch} onChange={e=>setYoutubeSearch(e.target.value)} placeholder="Buscar en YouTube..."/><button type="submit" disabled={youtubeSearching||!youtubeHasKey}>{youtubeSearching?<Loader2 size={16}/>:<Search size={16}/>}</button></form><div className="youtube-results">{youtubeResults.map((item:any)=>{const id=item.id.videoId;return <button key={id} type="button" onClick={()=>setYoutubeSelected(item)}><img src={item.snippet.thumbnails?.medium?.url||item.snippet.thumbnails?.default?.url} alt=""/><span><strong>{item.snippet.title}</strong><small>{item.snippet.channelTitle}</small></span></button>})}</div>{youtubeSelected&&<div><strong>{youtubeSelected.snippet.title}</strong><span>{youtubeSelected.snippet.channelTitle}</span></div>}</div>}
    {error&&<div className="composer-error">{error}</div>}
    {galleryOpen&&<div role="dialog" aria-modal="true" onClick={(e)=>{if(e.target===e.currentTarget)setGalleryOpen(false)}} style={{position:'fixed',inset:0,zIndex:10050,background:'rgba(21,39,56,.52)',display:'flex',alignItems:'center',justifyContent:'center',padding:24}}><div style={{width:'min(820px,96vw)',maxHeight:'88vh',overflow:'hidden',background:'#fff',border:'1px solid #ccd7e1',borderRadius:6,boxShadow:'0 14px 45px rgba(0,0,0,.22)',display:'flex',flexDirection:'column'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'14px 16px',borderBottom:'1px solid #e1e7ed'}}><strong style={{fontSize:16,color:'#314b63'}}>Elegir de mi galería</strong><button type="button" onClick={()=>setGalleryOpen(false)} style={{border:0,background:'transparent',color:'#63798c',fontSize:24,cursor:'pointer'}}>×</button></div>{galleryLoading?<div style={{padding:40,textAlign:'center',color:'#728396'}}>Cargando tus fotos...</div>:galleryPhotos.length===0?<div style={{padding:40,textAlign:'center',color:'#728396'}}>No tienes fotos en tu galería todavía.</div>:<div style={{padding:16,overflow:'auto',display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10}}>{galleryPhotos.map(photo=><button key={photo.id} type="button" onClick={()=>chooseGalleryPhoto(photo)} style={{position:'relative',aspectRatio:'1',border:'1px solid #d7e0e7',borderRadius:4,overflow:'hidden',background:'#edf2f6',padding:0,cursor:'pointer'}} title="Elegir esta foto"><img src={photo.url} alt={photo.caption||'Foto de mi galería'} loading="lazy" style={{display:'block',width:'100%',height:'100%',objectFit:'cover'}}/></button>)}</div>}</div></div>}
    <div className="composer-bottom"><div className="composer-modes"><button type="button" onClick={()=>handleModeChange('photo')} title="Foto"><ImageIcon size={18}/></button><button type="button" onClick={()=>handleModeChange('video')} title="Vídeo"><Video size={18}/></button><button type="button" onClick={()=>handleModeChange('music')} title="Música"><Music size={18}/></button><button type="button" onClick={()=>handleModeChange('poll')} title="Encuesta"><BarChart3 size={18}/></button><button type="button" ref={moreMenuRef} onClick={()=>setMoreMenuOpen(v=>!v)} title="Más"><List size={18}/></button></div>{renderPrivacy()}<button type="button" className="composer-publish" onClick={e=>void publish(e as any)} disabled={publishing}>{publishing?<Loader2 size={16}/>:buttonText}</button></div>
    <ComposerMenuPortal isOpen={moreMenuOpen} onClose={()=>setMoreMenuOpen(false)} triggerRef={moreMenuRef} onSelect={handleModeChange}/>
  </section>;
}
