import React, { createContext, useContext, useState, useEffect, useCallback, useRef } from 'react';
import { User, Photo, Album, FeedItem, WallComment, PrivateMessage, FriendRequest, Friendship, ChatMessage, ChatWindow, InkoriumNotification, AccessLog, UserActivity, UserPresence, ThemeMode, Track, RepeatMode, PhotoComment, PhotoTag, PhotoPrivacy, SocialEvent, EventAttendanceStatus, EventAttendee, EventComment, EventPhoto, ProfileVisit, TuentiPage, PagePost, UserInvitation, GameScore, CampusCommunity, CampusPost, CampusReply, getCountryByZone } from '../types';
import { supabase, isSupabaseConfigured } from '../lib/supabase';
import { fetchPosts, createPost } from '../lib/postsApi';
import { fetchPhotos, insertPhoto, addPhotoTagApi, removePhotoTagApi, updatePhotoPrivacyApi, addPhotoCommentApi, likePhotoApi } from '../lib/photosApi';
import { INITIAL_USERS, INITIAL_ALBUMS, INITIAL_PHOTOS, INITIAL_FEED, INITIAL_WALL_COMMENTS, INITIAL_FRIENDSHIPS, INITIAL_FRIEND_REQUESTS, INITIAL_MESSAGES, INITIAL_NOTIFICATIONS, INITIAL_ACCESS_LOGS, INITIAL_ACTIVITIES } from '../data/mockData';
import { INITIAL_EVENTS, INITIAL_PAGES, INITIAL_GAME_SCORES } from '../data/mockEventsAndPages';
import { INITIAL_CAMPUS_COMMUNITIES } from '../data/mockCampus';
import { INITIAL_MUSIC_TRACKS } from '../data/musicTracks';
import { musicAudioEngine } from '../utils/audioEngine';
import { appendMessageToConversation, updateMessageInConversation, normalizeUserId, broadcastCrossTabEvent, subscribeCrossTabEvents, markConversationAsRead, applyReadReceiptsToConversation, getStoredBlockedUserIds, saveStoredBlockedUserIds } from '../lib/chatHistory';
import { playMessageSound, playNotificationChime, playNudgeSound } from '../utils/sound';
import { RealtimeManager } from '../lib/realtimeManager';

const PHOTO_TAGS_STORAGE_KEY = 'inkorium:photo_tags';
const FALLBACK_AVATAR = 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&auto=format&fit=crop&q=80';

export function safeSetLocalStorage(key: string, value: string): void {
  if (typeof localStorage === 'undefined') return;
  try { localStorage.setItem(key, value); } catch (err) { console.warn(`[Inkorium] localStorage write failed for key "${key}":`, err); }
}
function getStoredTagsMap(): Record<string, PhotoTag[]> { if (typeof localStorage === 'undefined') return {}; try { const raw = localStorage.getItem(PHOTO_TAGS_STORAGE_KEY); if (!raw) return {}; const parsed = JSON.parse(raw); return parsed && typeof parsed === 'object' ? parsed : {}; } catch { return {}; } }
function getStoredTagsForPhoto(photoId: string): PhotoTag[] { if (!photoId) return []; const tags = getStoredTagsMap()[photoId]; return Array.isArray(tags) ? tags : []; }
function saveStoredTagsForPhoto(photoId: string, tags: PhotoTag[]) { if (typeof localStorage === 'undefined' || !photoId) return; try { const map = getStoredTagsMap(); map[photoId] = tags; safeSetLocalStorage(PHOTO_TAGS_STORAGE_KEY, JSON.stringify(map)); } catch {} }
function normalizeAvatar(avatar: unknown): string { const value = typeof avatar === 'string' ? avatar.trim() : ''; return value || FALLBACK_AVATAR; }

interface InkoriumContextType {
  currentUser: User; users: User[]; photos: Photo[]; albums: Album[]; feed: FeedItem[]; wallComments: WallComment[];
  messages: PrivateMessage[]; friendRequests: FriendRequest[]; friendships: Friendship[]; chatMessages: ChatMessage[]; notifications: InkoriumNotification[]; toasts: InkoriumNotification[]; accessLogs: AccessLog[]; activities: UserActivity[];
  activeChatWindows: ChatWindow[]; activeTab: 'inicio' | 'perfil' | 'gente' | 'fotos' | 'mensajes' | 'notificaciones' | 'ajustes' | 'musica' | 'eventos' | 'paginas' | 'juegos' | 'campus'; selectedUserId: string; selectedPhotoId: string | null; selectedAlbumId: string | null; composeRecipientId: string | null;
  isAntiAlgorithmMode: boolean; toggleAntiAlgorithmMode: () => void; events: SocialEvent[]; pages: TuentiPage[]; profileVisits: ProfileVisit[]; gameScores: GameScore[]; selectedEventId: string | null; setSelectedEventId: (id: string | null) => void; selectedPageId: string | null; setSelectedPageId: (id: string | null) => void; isInvitationsModalOpen: boolean; setIsInvitationsModalOpen: (open: boolean) => void;
  createEvent: (eventData: Omit<SocialEvent, 'id' | 'creadorId' | 'creadorNombre' | 'creadorAvatar' | 'asistentes' | 'comentarios'>) => string; rsvpEvent: (eventId: string, status: EventAttendanceStatus) => void; commentEvent: (eventId: string, text: string) => void; deleteEvent: (eventId: string) => void; addEventPhoto: (eventId: string, photoData: { url: string; caption?: string }) => void;
  createPage: (pageData: Omit<TuentiPage, 'id' | 'creadorId' | 'seguidores' | 'fechaCreacion' | 'posts'>) => string; toggleFollowPage: (pageId: string) => void; postPageComment: (pageId: string, text: string, fotoUrl?: string) => void; postPagePhoto: (pageId: string, photoData: EventPhoto) => void;
  recordProfileVisit: (targetUserId: string) => void; updateTopAmigos: (friendIds: string[]) => void; unreadMessagesCount: number; unreadNotificationsCount: number; pendingRequestsCount: number;
  isRealtimeSimulationEnabled: boolean; isLoggedIn: boolean; theme: ThemeMode; isDarkMode: boolean; setTheme: (theme: ThemeMode) => void; toggleTheme: () => void; currentTrack: Track | null; isMusicPlaying: boolean; musicPosition: number; musicDuration: number; musicVolume: number; isMusicMuted: boolean; isMusicShuffled: boolean; musicRepeatMode: RepeatMode; musicPlaylist: Track[]; isMusicPlayerOpen: boolean; isMusicPlayerMinimized: boolean;
  playTrack: (track: Track, openExpanded?: boolean) => void; pauseMusic: () => void; resumeMusic: () => void; togglePlayMusic: () => void; nextTrack: () => void; prevTrack: () => void; seekMusic: (seconds: number) => void; setMusicVolume: (volume: number) => void; toggleMusicMute: () => void; toggleMusicShuffle: () => void; toggleMusicRepeat: () => void; setIsMusicPlayerOpen: (open: boolean) => void; setIsMusicPlayerMinimized: (minimized: boolean) => void; openMusicPlayer: (track?: Track, openExpanded?: boolean) => void; addCustomTrack: (track: Omit<Track, 'id'>) => void; removeTrackFromPlaylist: (trackId: string) => void;
  setActiveTab: (tab: InkoriumContextType['activeTab']) => void; viewUserProfile: (userId: string) => void; openComposeMessage: (recipientId?: string) => void; viewPhoto: (photoId: string | null) => void; viewAlbum: (albumId: string | null) => void; setCurrentUserById: (userId: string) => void;
  login: (email: string, password?: string) => { success: boolean; error?: string }; loginAsUser: (userId: string) => void; logout: () => void; publishStatus: (statusText: string, attachedPhotoUrl?: string) => void; updateStatusText: (statusText: string) => void; updateUserPresence: (presencia: UserPresence) => void; likeFeedItem: (feedId: string) => void; commentFeedItem: (feedId: string, text: string) => void; postWallComment: (receptorId: string, text: string) => void; deleteWallComment: (commentId: string) => void; uploadPhoto: (titulo: string, albumId: string | null, archivoUrl: string, privacidad?: PhotoPrivacy, allowedUserIds?: string[]) => void; updatePhotoPrivacy: (photoId: string, privacidad: PhotoPrivacy, allowedUserIds?: string[]) => void; canUserViewPhoto: (photo: Photo, viewerUserId?: string) => boolean; addPhotoTag: (photoId: string, targetUserId: string, x: number, y: number) => void; removePhotoTag: (photoId: string, tagId: string) => void; addPhotoComment: (photoId: string, comentario: string) => void; likePhoto: (photoId: string) => void; setPhotoAsAvatar: (photoId: string) => void; deletePhoto: (photoId: string) => void; createAlbum: (nombre: string, descripcion?: string) => string | undefined; renameAlbum: (albumId: string, nuevoNombre: string) => void; deleteAlbum: (albumId: string) => void;
  sendFriendRequest: (targetUserId: string) => void; acceptFriendRequest: (requestId: string) => void; ignoreFriendRequest: (requestId: string) => void; removeFriendship: (targetUserId: string) => void; cancelFriendRequest: (targetUserId: string) => void; isFriend: (userId1: string, userId2: string) => boolean; hasPendingRequest: (fromId: string, toId: string) => boolean; getFriendsOf: (userId: string) => User[];
  sendPrivateMessage: (receptorId: string, asunto: string, mensaje: string) => void; markMessageAsRead: (messageId: string) => void; deleteMessage: (messageId: string) => void; deleteConversation: (targetUserId: string) => void; openChatWith: (targetUserId: string) => void; closeChat: (targetUserId: string) => void; toggleMinimizeChat: (targetUserId: string) => void; sendChatMessage: (targetUserId: string, text: string, imageUrl?: string, fileData?: { url: string; name: string; size?: number; type?: string }) => void; sendChatNudge: (targetUserId: string) => void; reactToChatMessage: (targetUserId: string, messageId: string, emoji: string) => void; sendChatTyping: (targetUserId: string, isTyping: boolean) => void; sendChatReadReceipt: (targetUserId: string, messageIds?: string[]) => void; setChatEstado: (estado: '1' | '0') => void;
  blockedUserIds: string[]; blockUser: (targetUserId: string) => void; unblockUser: (targetUserId: string) => void; isUserBlocked: (targetUserId: string) => boolean; logUserActivity: (activity: Omit<UserActivity, 'id' | 'timestamp'>) => void; deleteUserActivity: (activityId: string) => void; getUserActivities: (userId: string) => UserActivity[]; pushNotification: (notif: InkoriumNotification) => void; dismissToast: (toastId: string) => void; markNotificationAsRead: (notifId: string) => void; markAllNotificationsAsRead: () => void; deleteNotification: (notifId: string) => void; setIsRealtimeSimulationEnabled: (enabled: boolean) => void; simulateIncomingMessage: () => void; simulateWallComment: () => void; simulateFriendRequest: () => void; simulatePhotoInteraction: () => void;
  updateUserData: (data: Partial<User>) => void; resetToDefaultData: () => void; registerNewUser: (nombre: string, apellidos: string, email: string, sexo: 'h' | 'm', provincia: string, fnac: string, pais?: string, ciudad?: string) => void; selectedCampusId: string | null; setSelectedCampusId: (id: string | null) => void; campusCommunities: CampusCommunity[]; campusPosts: Record<string, CampusPost[]>; addCampusPost: (communityId: string, content: string, photoUrl?: string) => void; addCampusReply: (communityId: string, postId: string, content: string) => void; followCampusCommunity: (communityId: string) => void;
}

const InkoriumContext = createContext<InkoriumContextType | undefined>(undefined);
const EMPTY_USER: User = { id: '', nombre: '', apellidos: '', email: '', sexo: 'otro', fnac: '', provincia: '', ciudad: undefined, estado: '', estadoFecha: '', situacionSentimental: 'Soltero/a', avatar: FALLBACK_AVATAR, fechaReg: '', online: false, ultimoAcceso: '', chatEstado: '0' };
function isMockId(id: string | undefined | null): boolean { if (!id) return false; const s = String(id).toLowerCase(); return ['user-1','user-2','user-3','user-4','user-5','user-6','user-7','user-8','user-9','user-10','user-11','user-12','1','2','3','user-nightloot','nightloot','user-elena','user-carlos','user-laura'].includes(s); }

// Existing provider state, effects and actions continue below unchanged.
