import { StrictMode, useEffect, useMemo, useState, type FormEvent } from "react";
import { createRoot } from "react-dom/client";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "./lib/supabase";
import "./styles.css";

function Brand() { return <div className="brand"><img className="brand-mark" src="/inkorium-logo-white.svg" alt="" /><span>inkorium</span></div>; }
type Post = { id: number; text: string; time: string; likes: number };
type Page = "inicio" | "mensajes" | "personas" | "musica" | "buscar";
const initialPosts: Post[] = [{ id: 1, text: "Descubriendo nuevos sonidos para esta tarde. Que estais escuchando?", time: "hace 31 min", likes: 6 }, { id: 2, text: "Un espacio para compartir ideas, musica y momentos.", time: "hace 1 h", likes: 3 }];
const people = ["bg9222361", "Marta Creativa", "Alex Sonidos", "Clara Visual"]; const songs = ["MHR, EFY & SNEZ! - Hola", "Inalcanzable", "Atardecer en Madrid", "Noches de verano"];

function Feed({ session }: { session: Session }) {
  const username = session.user.email?.split("@")[0] || "usuario";
  const [page, setPage] = useState<Page>("inicio"); const [draft, setDraft] = useState(""); const [posts, setPosts] = useState(initialPosts); const [liked, setLiked] = useState<number[]>([]); const [query, setQuery] = useState(""); const [notifications, setNotifications] = useState(false); const [userMenu, setUserMenu] = useState(false); const [player, setPlayer] = useState(false); const [theme, setTheme] = useState("blue"); const [position, setPosition] = useState({ x: 24, y: 90 }); const [dragging, setDragging] = useState(false);
  const searchResults = useMemo(() => { const q = query.toLowerCase(); return { posts: posts.filter((item) => item.text.toLowerCase().includes(q)), people: people.filter((item) => item.toLowerCase().includes(q)), songs: songs.filter((item) => item.toLowerCase().includes(q)) }; }, [query, posts]);
  function publish(event: FormEvent) { event.preventDefault(); if (!draft.trim()) return; setPosts([{ id: Date.now(), text: draft.trim(), time: "ahora", likes: 0 }, ...posts]); setDraft(""); }
  function toggleLike(id: number) { const active = liked.includes(id); setLiked(active ? liked.filter((item) => item !== id) : [...liked, id]); setPosts(posts.map((post) => post.id === id ? { ...post, likes: post.likes + (active ? -1 : 1) } : post)); }
  const navigate = (next: Page) => { setPage(next); setNotifications(false); setUserMenu(false); };
  return <div className={`feed-app theme-${theme}`}>
    <header className="topbar"><button className="brand-button" onClick={() => navigate("inicio")}><Brand /></button><nav className="top-nav">{([["inicio", "Inicio"], ["mensajes", "Mensajes"], ["personas", "Personas"], ["musica", "Musica"]] as [Page, string][]).map(([id, label]) => <button className={page === id ? "active" : ""} onClick={() => navigate(id)} key={id}>{label}</button>)}</nav><form className="search-form" onSubmit={(event) => { event.preventDefault(); navigate("buscar"); }}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar personas, musica, videos..." /></form><div className="top-actions"><button className="icon-button" onClick={() => setNotifications(!notifications)} aria-label="Notificaciones">♧</button><button className="icon-button" onClick={() => setPlayer(!player)} aria-label="Reproductor">♫</button><button className="user-chip" onClick={() => setUserMenu(!userMenu)}><span className="avatar small">{username[0].toUpperCase()}</span>{username}⌄</button></div>{notifications && <div className="popover notifications"><strong>NOTIFICACIONES</strong><p>♡ A alguien le ha gustado tu publicación.</p><p>♫ Hay nueva música para descubrir.</p><p>● Tienes una sugerencia de amistad.</p><button onClick={() => setNotifications(false)}>Marcar todo como leído</button></div>}{userMenu && <div className="popover user-menu"><strong>{username}</strong><button onClick={() => navigate("personas")}>Mi perfil</button><button onClick={() => navigate("mensajes")}>Mis mensajes</button><hr /><span>Color de la web</span><div className="themes"><button className="theme-dot blue" onClick={() => setTheme("blue")} /><button className="theme-dot violet" onClick={() => setTheme("violet")} /><button className="theme-dot green" onClick={() => setTheme("green")} /><button className="theme-dot sunset" onClick={() => setTheme("sunset")} /></div><button onClick={() => void supabase.auth.signOut()}>Cerrar sesion</button></div>}</header>
    <div className="feed-layout"><aside className="left-column"><section className="profile-card panel"><div className="avatar profile-avatar">{username[0].toUpperCase()}</div><div><strong>{username}</strong><span>Mas rapido</span><em>● En linea</em><button onClick={() => navigate("personas")}>Ver mi perfil »</button></div></section><nav className="side-menu panel">{[["⌂", "Novedades", "inicio"], ["▧", "Fotos", "buscar"], ["▹", "Videos", "buscar"], ["♫", "Musica", "musica"], ["□", "Eventos", "buscar"], ["♧", "Grupos", "personas"], ["⚑", "Paginas", "personas"], ["▥", "Encuestas", "buscar"], ["▱", "Guardados", "buscar"], ["⚙", "Configuracion", "personas"]].map(([icon, label, id], index) => <button className={page === id && index === 0 ? "selected" : ""} onClick={() => navigate(id as Page)} key={label}><span>{icon}</span>{label}</button>)}</nav><section className="friends panel"><strong>AMIGOS CONECTADOS (1)</strong><div><span className="avatar tiny">B</span><button onClick={() => navigate("personas")}>bg9222361</button><i /></div><button className="see-all" onClick={() => navigate("personas")}>Ver todos »</button></section></aside>
      <main className="stream">{page === "inicio" && <><section className="composer panel"><div className="composer-row"><div className="avatar">{username[0].toUpperCase()}</div><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder={`Que estas pensando, ${username}?`} /></div><div className="composer-tools"><button>▧ Estado</button><button>▣ Foto</button><button>▹ Video</button><button onClick={() => { setPlayer(true); }}>♫ Musica</button><button>▧ Encuesta</button><button>▤ Noticia</button><button>☷ Mas⌄</button></div><div className="composer-footer"><span>◉ Publico⌄</span><button className="publish" onClick={publish}>Publicar</button></div></section>{posts.map((post) => <article className="post panel" key={post.id}><div className="post-head"><div className="avatar">{username[0].toUpperCase()}</div><div><strong>{username}</strong><span>{post.time} · ◉</span></div><button className="more">⌄</button></div><p className="post-text">{post.text}</p><div className="post-actions"><button onClick={() => toggleLike(post.id)} className={liked.includes(post.id) ? "is-liked" : ""}>♡ Me gusta <small>{post.likes || ""}</small></button><button>◯ Comentar</button><button>♧ Compartir</button><span>♡ {post.likes}</span></div></article>)}</>}{page === "buscar" && <SearchView query={query} results={searchResults} navigate={navigate} />}{page === "mensajes" && <MessagesView />}{page === "personas" && <PeopleView navigate={navigate} />}{page === "musica" && <MusicView onPlay={() => setPlayer(true)} />}</main>
      <aside className="right-column"><section className="panel right-card"><strong>SOLICITUDES</strong><button>Ver todas</button><p>No tienes solicitudes pendientes.</p></section><section className="panel right-card"><strong>EVENTOS DESTACADOS</strong><button>Ver todos</button><div className="event"><div className="event-image">♫</div><div><b>Descubre Inkorium</b><p>Comparte tus momentos y musica.</p></div></div><button className="outline">Añadir a mi calendario</button></section><section className="panel calendar"><strong>CALENDARIO</strong><span>▣</span><h3>Agosto 2026</h3><div className="week">Lu　 Ma　 Mi　 Ju　 Vi　 Sa　 Do</div><div className="days">{Array.from({ length: 31 }, (_, index) => <i className={index === 12 ? "today" : ""} key={index}>{index + 1}</i>)}</div></section></aside></div>
    <button className="chat">▢ Chat (0)</button>{player && <div className="mini-player" style={{ left: position.x, top: position.y }} onPointerDown={() => setDragging(true)} onPointerMove={(event) => { if (dragging) setPosition({ x: Math.max(5, event.clientX - 150), y: Math.max(65, event.clientY - 25) }); }} onPointerUp={() => setDragging(false)}><span className="drag-handle">⠿</span><button onClick={() => setPlayer(false)}>×</button><div className="album">♫</div><div><strong>Inkorium Mix</strong><small>Descubriendo sonidos...</small></div><span className="play">▶</span></div>}
  </div>;
}

function SearchView({ query, results, navigate }: { query: string; results: { posts: Post[]; people: string[]; songs: string[] }; navigate: (page: Page) => void }) { return <section className="content-view"><h1>Resultados de busqueda</h1><p className="view-subtitle">Resultados para <strong>{query || "todo"}</strong> en Inkorium</p><div className="result-grid"><div className="result-card panel"><h2>Personas</h2>{results.people.length ? results.people.map((person) => <button className="result-row" key={person}><span className="avatar tiny">{person[0]}</span>{person}</button>) : <p>No hay personas.</p>}</div><div className="result-card panel"><h2>Musica</h2>{results.songs.length ? results.songs.map((song) => <button className="result-row" key={song}><span className="music-square">♫</span>{song}</button>) : <p>No hay canciones.</p>}</div></div><div className="result-card panel"><h2>Publicaciones</h2>{results.posts.length ? results.posts.map((post) => <p className="search-post" key={post.id}>{post.text}<small>{post.time}</small></p>) : <p>No hay publicaciones.</p>}</div><button className="back-button" onClick={() => navigate("inicio")}>Volver al inicio</button></section>; }
function MessagesView() { return <section className="content-view"><h1>Mensajes</h1><p className="view-subtitle">Tus conversaciones en Inkorium.</p><div className="messages-layout panel"><div className="conversation selected"><span className="avatar">B</span><div><strong>bg9222361</strong><small>Conectado ahora</small></div><b>›</b></div><div className="empty-chat"><span>▢</span><h2>Selecciona una conversacion</h2><p>Elige un contacto para comenzar a hablar.</p></div></div></section>; }
function PeopleView({ navigate }: { navigate: (page: Page) => void }) { return <section className="content-view"><h1>Personas</h1><p className="view-subtitle">Encuentra gente con tus mismos intereses.</p><div className="people-grid">{people.map((person) => <div className="person-card panel" key={person}><span className="avatar profile-avatar">{person[0]}</span><h2>{person}</h2><p>Amante de la musica y las ideas.</p><button onClick={() => navigate("mensajes")}>Enviar mensaje</button></div>)}</div></section>; }
function MusicView({ onPlay }: { onPlay: () => void }) { return <section className="content-view"><h1>Musica</h1><p className="view-subtitle">Escucha, descubre y comparte nuevos sonidos.</p><div className="music-list panel">{songs.map((song, index) => <div className="song-row" key={song}><span className="music-square">♫</span><div><strong>{song}</strong><small>Inkorium Music · pista {index + 1}</small></div><button onClick={onPlay}>▶ Escuchar</button></div>)}</div></section>; }

function Login() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [mode, setMode] = useState<"login" | "signup">("login"); const [remember, setRemember] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); const result = mode === "login" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password }); setMessage(result.error ? result.error.message : mode === "login" ? "Sesion iniciada." : "Cuenta creada. Revisa tu correo si hace falta."); setBusy(false); } async function recoverPassword() { if (!email) { setMessage("Escribe tu email para recuperar la contraseña."); return; } setBusy(true); const result = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/` }); setMessage(result.error ? result.error.message : "Te hemos enviado un enlace para cambiar la contraseña."); setBusy(false); } return <main className="page"><Brand /><div className="card"><div className="card-heading"><h1>{mode === "login" ? "Iniciar sesión" : "Crear una cuenta"}</h1><p>{mode === "login" ? "Entra en tu espacio creativo." : "Empieza tu espacio creativo."}</p></div><form onSubmit={(event) => void submit(event)}><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Contraseña<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={6} required /></label><div className="form-options"><label className="remember"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} /><span>Recordarme en este equipo</span></label><button type="button" className="text-button" onClick={() => void recoverPassword()}>¿Contraseña olvidada?</button></div><button className="primary-button" disabled={busy}>{busy ? "Cargando..." : mode === "login" ? "Entrar" : "Crear cuenta"}</button></form>{message && <p className="message">{message}</p>}</div><div className="page-links"><button className="text-button" onClick={() => { setMode(mode === "login" ? "signup" : "login"); setMessage(""); }}>{mode === "login" ? "¿Quieres crear una cuenta?" : "¿Ya tienes una cuenta?"}</button><span>|</span><button className="text-button" onClick={() => void recoverPassword()}>Recordar contraseña</button></div></main>; }
function App() { const [session, setSession] = useState<Session | null>(null); useEffect(() => { void supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => data.subscription.unsubscribe(); }, []); return session ? <Feed session={session} /> : <Login />; }
createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
