/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMensajesRouteImport } from './routes/_authenticated/mensajes'
import { Route as AuthenticatedAmigosRouteImport } from './routes/_authenticated/amigos'
import { Route as AuthenticatedSidebarRouteImport } from './routes/_authenticated/_sidebar'
import { Route as AuthenticatedEventosRouteRouteImport } from './routes/_authenticated/eventos/route'
import { Route as AuthenticatedEventosIndexRouteImport } from './routes/_authenticated/eventos/index'
import { Route as AuthenticatedPerfilUsernameRouteImport } from './routes/_authenticated/perfil.$username'
import { Route as AuthenticatedMensajesUsernameRouteImport } from './routes/_authenticated/mensajes.$username'
import { Route as AuthenticatedEventosMisEventosRouteImport } from './routes/_authenticated/eventos/mis-eventos'
import { Route as AuthenticatedEventosCrearRouteImport } from './routes/_authenticated/eventos/crear'
import { Route as AuthenticatedEventosCalendarioRouteImport } from './routes/_authenticated/eventos/calendario'
import { Route as AuthenticatedEventosAmigosRouteImport } from './routes/_authenticated/eventos/amigos'
import { Route as AuthenticatedEventosIdRouteImport } from './routes/_authenticated/eventos/$id'
import { Route as AuthenticatedSidebarVideosRouteImport } from './routes/_authenticated/_sidebar/videos'
import { Route as AuthenticatedSidebarPaginasRouteImport } from './routes/_authenticated/_sidebar/paginas'
import { Route as AuthenticatedSidebarMusicaRouteImport } from './routes/_authenticated/_sidebar/musica'
import { Route as AuthenticatedSidebarGuardadosRouteImport } from './routes/_authenticated/_sidebar/guardados'
import { Route as AuthenticatedSidebarGruposRouteImport } from './routes/_authenticated/_sidebar/grupos'
import { Route as AuthenticatedSidebarFotosRouteImport } from './routes/_authenticated/_sidebar/fotos'
import { Route as AuthenticatedSidebarFeedRouteImport } from './routes/_authenticated/_sidebar/feed'
import { Route as AuthenticatedSidebarEncuestasRouteImport } from './routes/_authenticated/_sidebar/encuestas'
import { Route as AuthenticatedSidebarConfiguracionRouteImport } from './routes/_authenticated/_sidebar/configuracion'
import { Route as AuthenticatedEventosEditarIdRouteImport } from './routes/_authenticated/eventos/editar.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMensajesRoute = AuthenticatedMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmigosRoute = AuthenticatedAmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSidebarRoute = AuthenticatedSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosRouteRoute =
  AuthenticatedEventosRouteRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosIndexRoute =
  AuthenticatedEventosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventosRouteRoute,
  } as any)
const AuthenticatedPerfilUsernameRoute =
  AuthenticatedPerfilUsernameRouteImport.update({
    id: '/perfil/$username',
    path: '/perfil/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensajesUsernameRoute =
  AuthenticatedMensajesUsernameRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => AuthenticatedMensajesRoute,
  } as any)
const AuthenticatedEventosMisEventosRoute =
  AuthenticatedEventosMisEventosRouteImport.update({
    id: '/mis-eventos',
    path: '/mis-eventos',
    getParentRoute: () => AuthenticatedEventosRouteRoute,
  } as any)
const AuthenticatedEventosCrearRoute =
  AuthenticatedEventosCrearRouteImport.update({
    id: '/crear',
    path: '/crear',
    getParentRoute: () => AuthenticatedEventosRouteRoute,
  } as any)
const AuthenticatedEventosCalendarioRoute =
  AuthenticatedEventosCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedEventosRouteRoute,
  } as any)
const AuthenticatedEventosAmigosRoute =
  AuthenticatedEventosAmigosRouteImport.update({
    id: '/amigos',
    path: '/amigos',
    getParentRoute: () => AuthenticatedEventosRouteRoute,
  } as any)
const AuthenticatedEventosIdRoute = AuthenticatedEventosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEventosRouteRoute,
} as any)
const AuthenticatedSidebarVideosRoute =
  AuthenticatedSidebarVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarPaginasRoute =
  AuthenticatedSidebarPaginasRouteImport.update({
    id: '/paginas',
    path: '/paginas',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarMusicaRoute =
  AuthenticatedSidebarMusicaRouteImport.update({
    id: '/musica',
    path: '/musica',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarGuardadosRoute =
  AuthenticatedSidebarGuardadosRouteImport.update({
    id: '/guardados',
    path: '/guardados',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarGruposRoute =
  AuthenticatedSidebarGruposRouteImport.update({
    id: '/grupos',
    path: '/grupos',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarFotosRoute =
  AuthenticatedSidebarFotosRouteImport.update({
    id: '/fotos',
    path: '/fotos',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarFeedRoute =
  AuthenticatedSidebarFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarEncuestasRoute =
  AuthenticatedSidebarEncuestasRouteImport.update({
    id: '/encuestas',
    path: '/encuestas',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarConfiguracionRoute =
  AuthenticatedSidebarConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedEventosEditarIdRoute =
  AuthenticatedEventosEditarIdRouteImport.update({
    id: '/editar/$id',
    path: '/editar/$id',
    getParentRoute: () => AuthenticatedEventosRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/eventos': typeof AuthenticatedEventosRouteRouteWithChildren
  '/amigos': typeof AuthenticatedAmigosRoute
  '/mensajes': typeof AuthenticatedMensajesRouteWithChildren
  '/configuracion': typeof AuthenticatedSidebarConfiguracionRoute
  '/encuestas': typeof AuthenticatedSidebarEncuestasRoute
  '/feed': typeof AuthenticatedSidebarFeedRoute
  '/fotos': typeof AuthenticatedSidebarFotosRoute
  '/grupos': typeof AuthenticatedSidebarGruposRoute
  '/guardados': typeof AuthenticatedSidebarGuardadosRoute
  '/musica': typeof AuthenticatedSidebarMusicaRoute
  '/paginas': typeof AuthenticatedSidebarPaginasRoute
  '/videos': typeof AuthenticatedSidebarVideosRoute
  '/eventos/$id': typeof AuthenticatedEventosIdRoute
  '/eventos/amigos': typeof AuthenticatedEventosAmigosRoute
  '/eventos/calendario': typeof AuthenticatedEventosCalendarioRoute
  '/eventos/crear': typeof AuthenticatedEventosCrearRoute
  '/eventos/mis-eventos': typeof AuthenticatedEventosMisEventosRoute
  '/mensajes/$username': typeof AuthenticatedMensajesUsernameRoute
  '/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
  '/eventos/': typeof AuthenticatedEventosIndexRoute
  '/eventos/editar/$id': typeof AuthenticatedEventosEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/mensajes': typeof AuthenticatedMensajesRouteWithChildren
  '/configuracion': typeof AuthenticatedSidebarConfiguracionRoute
  '/encuestas': typeof AuthenticatedSidebarEncuestasRoute
  '/feed': typeof AuthenticatedSidebarFeedRoute
  '/fotos': typeof AuthenticatedSidebarFotosRoute
  '/grupos': typeof AuthenticatedSidebarGruposRoute
  '/guardados': typeof AuthenticatedSidebarGuardadosRoute
  '/musica': typeof AuthenticatedSidebarMusicaRoute
  '/paginas': typeof AuthenticatedSidebarPaginasRoute
  '/videos': typeof AuthenticatedSidebarVideosRoute
  '/eventos/$id': typeof AuthenticatedEventosIdRoute
  '/eventos/amigos': typeof AuthenticatedEventosAmigosRoute
  '/eventos/calendario': typeof AuthenticatedEventosCalendarioRoute
  '/eventos/crear': typeof AuthenticatedEventosCrearRoute
  '/eventos/mis-eventos': typeof AuthenticatedEventosMisEventosRoute
  '/mensajes/$username': typeof AuthenticatedMensajesUsernameRoute
  '/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
  '/eventos': typeof AuthenticatedEventosIndexRoute
  '/eventos/editar/$id': typeof AuthenticatedEventosEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRouteRouteWithChildren
  '/_authenticated/_sidebar': typeof AuthenticatedSidebarRouteWithChildren
  '/_authenticated/amigos': typeof AuthenticatedAmigosRoute
  '/_authenticated/mensajes': typeof AuthenticatedMensajesRouteWithChildren
  '/_authenticated/_sidebar/configuracion': typeof AuthenticatedSidebarConfiguracionRoute
  '/_authenticated/_sidebar/encuestas': typeof AuthenticatedSidebarEncuestasRoute
  '/_authenticated/_sidebar/feed': typeof AuthenticatedSidebarFeedRoute
  '/_authenticated/_sidebar/fotos': typeof AuthenticatedSidebarFotosRoute
  '/_authenticated/_sidebar/grupos': typeof AuthenticatedSidebarGruposRoute
  '/_authenticated/_sidebar/guardados': typeof AuthenticatedSidebarGuardadosRoute
  '/_authenticated/_sidebar/musica': typeof AuthenticatedSidebarMusicaRoute
  '/_authenticated/_sidebar/paginas': typeof AuthenticatedSidebarPaginasRoute
  '/_authenticated/_sidebar/videos': typeof AuthenticatedSidebarVideosRoute
  '/_authenticated/eventos/$id': typeof AuthenticatedEventosIdRoute
  '/_authenticated/eventos/amigos': typeof AuthenticatedEventosAmigosRoute
  '/_authenticated/eventos/calendario': typeof AuthenticatedEventosCalendarioRoute
  '/_authenticated/eventos/crear': typeof AuthenticatedEventosCrearRoute
  '/_authenticated/eventos/mis-eventos': typeof AuthenticatedEventosMisEventosRoute
  '/_authenticated/mensajes/$username': typeof AuthenticatedMensajesUsernameRoute
  '/_authenticated/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexRoute
  '/_authenticated/eventos/editar/$id': typeof AuthenticatedEventosEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/eventos'
    | '/amigos'
    | '/mensajes'
    | '/configuracion'
    | '/encuestas'
    | '/feed'
    | '/fotos'
    | '/grupos'
    | '/guardados'
    | '/musica'
    | '/paginas'
    | '/videos'
    | '/eventos/$id'
    | '/eventos/amigos'
    | '/eventos/calendario'
    | '/eventos/crear'
    | '/eventos/mis-eventos'
    | '/mensajes/$username'
    | '/perfil/$username'
    | '/eventos/'
    | '/eventos/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/amigos'
    | '/mensajes'
    | '/configuracion'
    | '/encuestas'
    | '/feed'
    | '/fotos'
    | '/grupos'
    | '/guardados'
    | '/musica'
    | '/paginas'
    | '/videos'
    | '/eventos/$id'
    | '/eventos/amigos'
    | '/eventos/calendario'
    | '/eventos/crear'
    | '/eventos/mis-eventos'
    | '/mensajes/$username'
    | '/perfil/$username'
    | '/eventos'
    | '/eventos/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/eventos'
    | '/_authenticated/_sidebar'
    | '/_authenticated/amigos'
    | '/_authenticated/mensajes'
    | '/_authenticated/_sidebar/configuracion'
    | '/_authenticated/_sidebar/encuestas'
    | '/_authenticated/_sidebar/feed'
    | '/_authenticated/_sidebar/fotos'
    | '/_authenticated/_sidebar/grupos'
    | '/_authenticated/_sidebar/guardados'
    | '/_authenticated/_sidebar/musica'
    | '/_authenticated/_sidebar/paginas'
    | '/_authenticated/_sidebar/videos'
    | '/_authenticated/eventos/$id'
    | '/_authenticated/eventos/amigos'
    | '/_authenticated/eventos/calendario'
    | '/_authenticated/eventos/crear'
    | '/_authenticated/eventos/mis-eventos'
    | '/_authenticated/mensajes/$username'
    | '/_authenticated/perfil/$username'
    | '/_authenticated/eventos/'
    | '/_authenticated/eventos/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mensajes': {
      id: '/_authenticated/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof AuthenticatedMensajesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/amigos': {
      id: '/_authenticated/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AuthenticatedAmigosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_sidebar': {
      id: '/_authenticated/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSidebarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthenticatedEventosIndexRouteImport
      parentRoute: typeof AuthenticatedEventosRouteRoute
    }
    '/_authenticated/perfil/$username': {
      id: '/_authenticated/perfil/$username'
      path: '/perfil/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof AuthenticatedPerfilUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensajes/$username': {
      id: '/_authenticated/mensajes/$username'
      path: '/$username'
      fullPath: '/mensajes/$username'
      preLoaderRoute: typeof AuthenticatedMensajesUsernameRouteImport
      parentRoute: typeof AuthenticatedMensajesRoute
    }
    '/_authenticated/eventos/mis-eventos': {
      id: '/_authenticated/eventos/mis-eventos'
      path: '/mis-eventos'
      fullPath: '/eventos/mis-eventos'
      preLoaderRoute: typeof AuthenticatedEventosMisEventosRouteImport
      parentRoute: typeof AuthenticatedEventosRouteRoute
    }
    '/_authenticated/eventos/crear': {
      id: '/_authenticated/eventos/crear'
      path: '/crear'
      fullPath: '/eventos/crear'
      preLoaderRoute: typeof AuthenticatedEventosCrearRouteImport
      parentRoute: typeof AuthenticatedEventosRouteRoute
    }
    '/_authenticated/eventos/calendario': {
      id: '/_authenticated/eventos/calendario'
      path: '/calendario'
      fullPath: '/eventos/calendario'
      preLoaderRoute: typeof AuthenticatedEventosCalendarioRouteImport
      parentRoute: typeof AuthenticatedEventosRouteRoute
    }
    '/_authenticated/eventos/amigos': {
      id: '/_authenticated/eventos/amigos'
      path: '/amigos'
      fullPath: '/eventos/amigos'
      preLoaderRoute: typeof AuthenticatedEventosAmigosRouteImport
      parentRoute: typeof AuthenticatedEventosRouteRoute
    }
    '/_authenticated/eventos/$id': {
      id: '/_authenticated/eventos/$id'
      path: '/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof AuthenticatedEventosIdRouteImport
      parentRoute: typeof AuthenticatedEventosRouteRoute
    }
    '/_authenticated/_sidebar/videos': {
      id: '/_authenticated/_sidebar/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedSidebarVideosRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/paginas': {
      id: '/_authenticated/_sidebar/paginas'
      path: '/paginas'
      fullPath: '/paginas'
      preLoaderRoute: typeof AuthenticatedSidebarPaginasRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/musica': {
      id: '/_authenticated/_sidebar/musica'
      path: '/musica'
      fullPath: '/musica'
      preLoaderRoute: typeof AuthenticatedSidebarMusicaRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/guardados': {
      id: '/_authenticated/_sidebar/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof AuthenticatedSidebarGuardadosRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/grupos': {
      id: '/_authenticated/_sidebar/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedSidebarGruposRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/fotos': {
      id: '/_authenticated/_sidebar/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof AuthenticatedSidebarFotosRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/feed': {
      id: '/_authenticated/_sidebar/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedSidebarFeedRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/encuestas': {
      id: '/_authenticated/_sidebar/encuestas'
      path: '/encuestas'
      fullPath: '/encuestas'
      preLoaderRoute: typeof AuthenticatedSidebarEncuestasRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/configuracion': {
      id: '/_authenticated/_sidebar/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedSidebarConfiguracionRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/eventos/editar/$id': {
      id: '/_authenticated/eventos/editar/$id'
      path: '/editar/$id'
      fullPath: '/eventos/editar/$id'
      preLoaderRoute: typeof AuthenticatedEventosEditarIdRouteImport
      parentRoute: typeof AuthenticatedEventosRouteRoute
    }
  }
}

interface AuthenticatedEventosRouteRouteChildren {
  AuthenticatedEventosIdRoute: typeof AuthenticatedEventosIdRoute
  AuthenticatedEventosAmigosRoute: typeof AuthenticatedEventosAmigosRoute
  AuthenticatedEventosCalendarioRoute: typeof AuthenticatedEventosCalendarioRoute
  AuthenticatedEventosCrearRoute: typeof AuthenticatedEventosCrearRoute
  AuthenticatedEventosMisEventosRoute: typeof AuthenticatedEventosMisEventosRoute
  AuthenticatedEventosIndexRoute: typeof AuthenticatedEventosIndexRoute
  AuthenticatedEventosEditarIdRoute: typeof AuthenticatedEventosEditarIdRoute
}

const AuthenticatedEventosRouteRouteChildren: AuthenticatedEventosRouteRouteChildren =
  {
    AuthenticatedEventosIdRoute: AuthenticatedEventosIdRoute,
    AuthenticatedEventosAmigosRoute: AuthenticatedEventosAmigosRoute,
    AuthenticatedEventosCalendarioRoute: AuthenticatedEventosCalendarioRoute,
    AuthenticatedEventosCrearRoute: AuthenticatedEventosCrearRoute,
    AuthenticatedEventosMisEventosRoute: AuthenticatedEventosMisEventosRoute,
    AuthenticatedEventosIndexRoute: AuthenticatedEventosIndexRoute,
    AuthenticatedEventosEditarIdRoute: AuthenticatedEventosEditarIdRoute,
  }

const AuthenticatedEventosRouteRouteWithChildren =
  AuthenticatedEventosRouteRoute._addFileChildren(
    AuthenticatedEventosRouteRouteChildren,
  )

interface AuthenticatedSidebarRouteChildren {
  AuthenticatedSidebarConfiguracionRoute: typeof AuthenticatedSidebarConfiguracionRoute
  AuthenticatedSidebarEncuestasRoute: typeof AuthenticatedSidebarEncuestasRoute
  AuthenticatedSidebarFeedRoute: typeof AuthenticatedSidebarFeedRoute
  AuthenticatedSidebarFotosRoute: typeof AuthenticatedSidebarFotosRoute
  AuthenticatedSidebarGruposRoute: typeof AuthenticatedSidebarGruposRoute
  AuthenticatedSidebarGuardadosRoute: typeof AuthenticatedSidebarGuardadosRoute
  AuthenticatedSidebarMusicaRoute: typeof AuthenticatedSidebarMusicaRoute
  AuthenticatedSidebarPaginasRoute: typeof AuthenticatedSidebarPaginasRoute
  AuthenticatedSidebarVideosRoute: typeof AuthenticatedSidebarVideosRoute
}

const AuthenticatedSidebarRouteChildren: AuthenticatedSidebarRouteChildren = {
  AuthenticatedSidebarConfiguracionRoute:
    AuthenticatedSidebarConfiguracionRoute,
  AuthenticatedSidebarEncuestasRoute: AuthenticatedSidebarEncuestasRoute,
  AuthenticatedSidebarFeedRoute: AuthenticatedSidebarFeedRoute,
  AuthenticatedSidebarFotosRoute: AuthenticatedSidebarFotosRoute,
  AuthenticatedSidebarGruposRoute: AuthenticatedSidebarGruposRoute,
  AuthenticatedSidebarGuardadosRoute: AuthenticatedSidebarGuardadosRoute,
  AuthenticatedSidebarMusicaRoute: AuthenticatedSidebarMusicaRoute,
  AuthenticatedSidebarPaginasRoute: AuthenticatedSidebarPaginasRoute,
  AuthenticatedSidebarVideosRoute: AuthenticatedSidebarVideosRoute,
}

const AuthenticatedSidebarRouteWithChildren =
  AuthenticatedSidebarRoute._addFileChildren(AuthenticatedSidebarRouteChildren)

interface AuthenticatedMensajesRouteChildren {
  AuthenticatedMensajesUsernameRoute: typeof AuthenticatedMensajesUsernameRoute
}

const AuthenticatedMensajesRouteChildren: AuthenticatedMensajesRouteChildren = {
  AuthenticatedMensajesUsernameRoute: AuthenticatedMensajesUsernameRoute,
}

const AuthenticatedMensajesRouteWithChildren =
  AuthenticatedMensajesRoute._addFileChildren(
    AuthenticatedMensajesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEventosRouteRoute: typeof AuthenticatedEventosRouteRouteWithChildren
  AuthenticatedSidebarRoute: typeof AuthenticatedSidebarRouteWithChildren
  AuthenticatedAmigosRoute: typeof AuthenticatedAmigosRoute
  AuthenticatedMensajesRoute: typeof AuthenticatedMensajesRouteWithChildren
  AuthenticatedPerfilUsernameRoute: typeof AuthenticatedPerfilUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEventosRouteRoute: AuthenticatedEventosRouteRouteWithChildren,
  AuthenticatedSidebarRoute: AuthenticatedSidebarRouteWithChildren,
  AuthenticatedAmigosRoute: AuthenticatedAmigosRoute,
  AuthenticatedMensajesRoute: AuthenticatedMensajesRouteWithChildren,
  AuthenticatedPerfilUsernameRoute: AuthenticatedPerfilUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
