/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMensajesRouteImport } from './routes/_authenticated/mensajes'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedAmigosRouteImport } from './routes/_authenticated/amigos'
import { Route as AuthenticatedSidebarRouteImport } from './routes/_authenticated/_sidebar'
import { Route as AuthenticatedPerfilUsernameRouteImport } from './routes/_authenticated/perfil.$username'
import { Route as AuthenticatedMensajesUsernameRouteImport } from './routes/_authenticated/mensajes.$username'
import { Route as AuthenticatedSidebarVideosRouteImport } from './routes/_authenticated/_sidebar/videos'
import { Route as AuthenticatedSidebarPaginasRouteImport } from './routes/_authenticated/_sidebar/paginas'
import { Route as AuthenticatedSidebarMusicaRouteImport } from './routes/_authenticated/_sidebar/musica'
import { Route as AuthenticatedSidebarGuardadosRouteImport } from './routes/_authenticated/_sidebar/guardados'
import { Route as AuthenticatedSidebarGruposRouteImport } from './routes/_authenticated/_sidebar/grupos'
import { Route as AuthenticatedSidebarFotosRouteImport } from './routes/_authenticated/_sidebar/fotos'
import { Route as AuthenticatedSidebarFeedRouteImport } from './routes/_authenticated/_sidebar/feed'
import { Route as AuthenticatedSidebarEncuestasRouteImport } from './routes/_authenticated/_sidebar/encuestas'
import { Route as AuthenticatedSidebarConfiguracionRouteImport } from './routes/_authenticated/_sidebar/configuracion'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMensajesRoute = AuthenticatedMensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmigosRoute = AuthenticatedAmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSidebarRoute = AuthenticatedSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilUsernameRoute =
  AuthenticatedPerfilUsernameRouteImport.update({
    id: '/perfil/$username',
    path: '/perfil/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensajesUsernameRoute =
  AuthenticatedMensajesUsernameRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => AuthenticatedMensajesRoute,
  } as any)
const AuthenticatedSidebarVideosRoute =
  AuthenticatedSidebarVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarPaginasRoute =
  AuthenticatedSidebarPaginasRouteImport.update({
    id: '/paginas',
    path: '/paginas',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarMusicaRoute =
  AuthenticatedSidebarMusicaRouteImport.update({
    id: '/musica',
    path: '/musica',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarGuardadosRoute =
  AuthenticatedSidebarGuardadosRouteImport.update({
    id: '/guardados',
    path: '/guardados',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarGruposRoute =
  AuthenticatedSidebarGruposRouteImport.update({
    id: '/grupos',
    path: '/grupos',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarFotosRoute =
  AuthenticatedSidebarFotosRouteImport.update({
    id: '/fotos',
    path: '/fotos',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarFeedRoute =
  AuthenticatedSidebarFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarEncuestasRoute =
  AuthenticatedSidebarEncuestasRouteImport.update({
    id: '/encuestas',
    path: '/encuestas',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)
const AuthenticatedSidebarConfiguracionRoute =
  AuthenticatedSidebarConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedSidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/mensajes': typeof AuthenticatedMensajesRouteWithChildren
  '/configuracion': typeof AuthenticatedSidebarConfiguracionRoute
  '/encuestas': typeof AuthenticatedSidebarEncuestasRoute
  '/feed': typeof AuthenticatedSidebarFeedRoute
  '/fotos': typeof AuthenticatedSidebarFotosRoute
  '/grupos': typeof AuthenticatedSidebarGruposRoute
  '/guardados': typeof AuthenticatedSidebarGuardadosRoute
  '/musica': typeof AuthenticatedSidebarMusicaRoute
  '/paginas': typeof AuthenticatedSidebarPaginasRoute
  '/videos': typeof AuthenticatedSidebarVideosRoute
  '/mensajes/$username': typeof AuthenticatedMensajesUsernameRoute
  '/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/mensajes': typeof AuthenticatedMensajesRouteWithChildren
  '/configuracion': typeof AuthenticatedSidebarConfiguracionRoute
  '/encuestas': typeof AuthenticatedSidebarEncuestasRoute
  '/feed': typeof AuthenticatedSidebarFeedRoute
  '/fotos': typeof AuthenticatedSidebarFotosRoute
  '/grupos': typeof AuthenticatedSidebarGruposRoute
  '/guardados': typeof AuthenticatedSidebarGuardadosRoute
  '/musica': typeof AuthenticatedSidebarMusicaRoute
  '/paginas': typeof AuthenticatedSidebarPaginasRoute
  '/videos': typeof AuthenticatedSidebarVideosRoute
  '/mensajes/$username': typeof AuthenticatedMensajesUsernameRoute
  '/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_sidebar': typeof AuthenticatedSidebarRouteWithChildren
  '/_authenticated/amigos': typeof AuthenticatedAmigosRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/mensajes': typeof AuthenticatedMensajesRouteWithChildren
  '/_authenticated/_sidebar/configuracion': typeof AuthenticatedSidebarConfiguracionRoute
  '/_authenticated/_sidebar/encuestas': typeof AuthenticatedSidebarEncuestasRoute
  '/_authenticated/_sidebar/feed': typeof AuthenticatedSidebarFeedRoute
  '/_authenticated/_sidebar/fotos': typeof AuthenticatedSidebarFotosRoute
  '/_authenticated/_sidebar/grupos': typeof AuthenticatedSidebarGruposRoute
  '/_authenticated/_sidebar/guardados': typeof AuthenticatedSidebarGuardadosRoute
  '/_authenticated/_sidebar/musica': typeof AuthenticatedSidebarMusicaRoute
  '/_authenticated/_sidebar/paginas': typeof AuthenticatedSidebarPaginasRoute
  '/_authenticated/_sidebar/videos': typeof AuthenticatedSidebarVideosRoute
  '/_authenticated/mensajes/$username': typeof AuthenticatedMensajesUsernameRoute
  '/_authenticated/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/amigos'
    | '/eventos'
    | '/mensajes'
    | '/configuracion'
    | '/encuestas'
    | '/feed'
    | '/fotos'
    | '/grupos'
    | '/guardados'
    | '/musica'
    | '/paginas'
    | '/videos'
    | '/mensajes/$username'
    | '/perfil/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/amigos'
    | '/eventos'
    | '/mensajes'
    | '/configuracion'
    | '/encuestas'
    | '/feed'
    | '/fotos'
    | '/grupos'
    | '/guardados'
    | '/musica'
    | '/paginas'
    | '/videos'
    | '/mensajes/$username'
    | '/perfil/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_sidebar'
    | '/_authenticated/amigos'
    | '/_authenticated/eventos'
    | '/_authenticated/mensajes'
    | '/_authenticated/_sidebar/configuracion'
    | '/_authenticated/_sidebar/encuestas'
    | '/_authenticated/_sidebar/feed'
    | '/_authenticated/_sidebar/fotos'
    | '/_authenticated/_sidebar/grupos'
    | '/_authenticated/_sidebar/guardados'
    | '/_authenticated/_sidebar/musica'
    | '/_authenticated/_sidebar/paginas'
    | '/_authenticated/_sidebar/videos'
    | '/_authenticated/mensajes/$username'
    | '/_authenticated/perfil/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mensajes': {
      id: '/_authenticated/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof AuthenticatedMensajesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/amigos': {
      id: '/_authenticated/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AuthenticatedAmigosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_sidebar': {
      id: '/_authenticated/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSidebarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil/$username': {
      id: '/_authenticated/perfil/$username'
      path: '/perfil/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof AuthenticatedPerfilUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensajes/$username': {
      id: '/_authenticated/mensajes/$username'
      path: '/$username'
      fullPath: '/mensajes/$username'
      preLoaderRoute: typeof AuthenticatedMensajesUsernameRouteImport
      parentRoute: typeof AuthenticatedMensajesRoute
    }
    '/_authenticated/_sidebar/videos': {
      id: '/_authenticated/_sidebar/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedSidebarVideosRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/paginas': {
      id: '/_authenticated/_sidebar/paginas'
      path: '/paginas'
      fullPath: '/paginas'
      preLoaderRoute: typeof AuthenticatedSidebarPaginasRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/musica': {
      id: '/_authenticated/_sidebar/musica'
      path: '/musica'
      fullPath: '/musica'
      preLoaderRoute: typeof AuthenticatedSidebarMusicaRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/guardados': {
      id: '/_authenticated/_sidebar/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof AuthenticatedSidebarGuardadosRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/grupos': {
      id: '/_authenticated/_sidebar/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedSidebarGruposRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/fotos': {
      id: '/_authenticated/_sidebar/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof AuthenticatedSidebarFotosRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/feed': {
      id: '/_authenticated/_sidebar/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedSidebarFeedRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/encuestas': {
      id: '/_authenticated/_sidebar/encuestas'
      path: '/encuestas'
      fullPath: '/encuestas'
      preLoaderRoute: typeof AuthenticatedSidebarEncuestasRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
    '/_authenticated/_sidebar/configuracion': {
      id: '/_authenticated/_sidebar/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedSidebarConfiguracionRouteImport
      parentRoute: typeof AuthenticatedSidebarRoute
    }
  }
}

interface AuthenticatedSidebarRouteChildren {
  AuthenticatedSidebarConfiguracionRoute: typeof AuthenticatedSidebarConfiguracionRoute
  AuthenticatedSidebarEncuestasRoute: typeof AuthenticatedSidebarEncuestasRoute
  AuthenticatedSidebarFeedRoute: typeof AuthenticatedSidebarFeedRoute
  AuthenticatedSidebarFotosRoute: typeof AuthenticatedSidebarFotosRoute
  AuthenticatedSidebarGruposRoute: typeof AuthenticatedSidebarGruposRoute
  AuthenticatedSidebarGuardadosRoute: typeof AuthenticatedSidebarGuardadosRoute
  AuthenticatedSidebarMusicaRoute: typeof AuthenticatedSidebarMusicaRoute
  AuthenticatedSidebarPaginasRoute: typeof AuthenticatedSidebarPaginasRoute
  AuthenticatedSidebarVideosRoute: typeof AuthenticatedSidebarVideosRoute
}

const AuthenticatedSidebarRouteChildren: AuthenticatedSidebarRouteChildren = {
  AuthenticatedSidebarConfiguracionRoute:
    AuthenticatedSidebarConfiguracionRoute,
  AuthenticatedSidebarEncuestasRoute: AuthenticatedSidebarEncuestasRoute,
  AuthenticatedSidebarFeedRoute: AuthenticatedSidebarFeedRoute,
  AuthenticatedSidebarFotosRoute: AuthenticatedSidebarFotosRoute,
  AuthenticatedSidebarGruposRoute: AuthenticatedSidebarGruposRoute,
  AuthenticatedSidebarGuardadosRoute: AuthenticatedSidebarGuardadosRoute,
  AuthenticatedSidebarMusicaRoute: AuthenticatedSidebarMusicaRoute,
  AuthenticatedSidebarPaginasRoute: AuthenticatedSidebarPaginasRoute,
  AuthenticatedSidebarVideosRoute: AuthenticatedSidebarVideosRoute,
}

const AuthenticatedSidebarRouteWithChildren =
  AuthenticatedSidebarRoute._addFileChildren(AuthenticatedSidebarRouteChildren)

interface AuthenticatedMensajesRouteChildren {
  AuthenticatedMensajesUsernameRoute: typeof AuthenticatedMensajesUsernameRoute
}

const AuthenticatedMensajesRouteChildren: AuthenticatedMensajesRouteChildren = {
  AuthenticatedMensajesUsernameRoute: AuthenticatedMensajesUsernameRoute,
}

const AuthenticatedMensajesRouteWithChildren =
  AuthenticatedMensajesRoute._addFileChildren(
    AuthenticatedMensajesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSidebarRoute: typeof AuthenticatedSidebarRouteWithChildren
  AuthenticatedAmigosRoute: typeof AuthenticatedAmigosRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedMensajesRoute: typeof AuthenticatedMensajesRouteWithChildren
  AuthenticatedPerfilUsernameRoute: typeof AuthenticatedPerfilUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSidebarRoute: AuthenticatedSidebarRouteWithChildren,
  AuthenticatedAmigosRoute: AuthenticatedAmigosRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedMensajesRoute: AuthenticatedMensajesRouteWithChildren,
  AuthenticatedPerfilUsernameRoute: AuthenticatedPerfilUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
