ALTER TABLE public.events ADD COLUMN slug TEXT UNIQUE;
ALTER TABLE public.events ADD COLUMN category TEXT;
ALTER TABLE public.events ADD COLUMN short_description TEXT;
ALTER TABLE public.events ADD COLUMN end_date DATE;
ALTER TABLE public.events ADD COLUMN end_time TIME;
ALTER TABLE public.events ADD COLUMN city TEXT;
ALTER TABLE public.events ADD COLUMN address TEXT;
ALTER TABLE public.events ADD COLUMN venue TEXT;
ALTER TABLE public.events ADD COLUMN postal_code TEXT;
ALTER TABLE public.events ADD COLUMN country TEXT;
ALTER TABLE public.events ADD COLUMN show_map BOOLEAN DEFAULT false;
ALTER TABLE public.events ADD COLUMN cover_url TEXT;
ALTER TABLE public.events ADD COLUMN poster_url TEXT;
ALTER TABLE public.events ADD COLUMN is_paid BOOLEAN DEFAULT false;
ALTER TABLE public.events ADD COLUMN price TEXT;
ALTER TABLE public.events ADD COLUMN ticket_url TEXT;
ALTER TABLE public.events ADD COLUMN organizer_name TEXT;
ALTER TABLE public.events ADD COLUMN organizer_email TEXT;
ALTER TABLE public.events ADD COLUMN organizer_website TEXT;
ALTER TABLE public.events ADD COLUMN organizer_instagram TEXT;
ALTER TABLE public.events ADD COLUMN organizer_facebook TEXT;
ALTER TABLE public.events ADD COLUMN organizer_x TEXT;
ALTER TABLE public.events ADD COLUMN organizer_tiktok TEXT;
ALTER TABLE public.events ADD COLUMN max_attendees INT;
ALTER TABLE public.events ADD COLUMN show_attendees BOOLEAN DEFAULT true;
ALTER TABLE public.events ADD COLUMN allow_comments BOOLEAN DEFAULT true;
ALTER TABLE public.events ADD COLUMN allow_shares BOOLEAN DEFAULT true;
ALTER TABLE public.events ADD COLUMN allow_photos BOOLEAN DEFAULT true;
ALTER TABLE public.events ADD COLUMN privacy TEXT DEFAULT 'public';
ALTER TABLE public.events ADD COLUMN tags TEXT[] DEFAULT '{}';
ALTER TABLE public.events ADD COLUMN youtube_song TEXT;
ALTER TABLE public.events ADD COLUMN youtube_playlist TEXT;
ALTER TABLE public.events ADD COLUMN status TEXT DEFAULT 'published';
