import { Link, useNavigate, useRouter } from '@tanstack/react-router';
import { Bell, CalendarDays, ChevronDown, Home, Image as ImageIcon, LogOut, Music2, Settings, Users, Video } from 'lucide-react';
import { useAuth } from '../hooks/useAuth';
import { useLogout } from '../features/auth/hooks/useAuth';

const friends = [
  { name: 'Amigo 1', image: 21, music: 'Escuchando Spotify' },
  { name: 'Amigo 2', image: 22, music: 'Escuchando Spotify' },
  { name: 'Amigo 3', image: 23, music: 'Escuchando Spotify' },
];
const avatarUrl = (user: ReturnType<typeof useAuth>['user']) => user?.user_metadata?.avatar_url || `https://ui-avatars.com/api/?name=${encodeURIComponent(user?.user_metadata?.full_name || 'User')}`;
const card: React.CSSProperties = { background:'#fff', border:'1px solid #d9e1e8', padding:16, boxShadow:'0 1px 2px rgba(0,0,0,.04)' };

export function MainLayout({ children }: { children: React.ReactNode }) {
  const { user } = useAuth(); const logoutMutation = useLogout(); const navigate = useNavigate(); const router = useRouter();
  const avatar = avatarUrl(user); const displayName = user?.user_metadata?.full_name || user?.user_metadata?.username || 'Usuario';
  const handleSignOut = () => logoutMutation.mutate(undefined, { onSuccess: async () => { await router.invalidate(); navigate({ to:'/login' }); } });
  return <div style={{minHeight:'100vh',background:'#f4f6f8',color:'#26364a',fontFamily:'Arial,Helvetica,sans-serif'}}>
    <header style={{height:58,background:'#0755b8',color:'#fff',boxShadow:'0 1px 4px rgba(0,0,0,.18)'}}><div style={{height:'100%',maxWidth:1500,margin:'0 auto',padding:'0 18px',display:'flex',alignItems:'center'}}>
      <Link to="/feed" style={{width:205,height:'100%',display:'flex',alignItems:'center',gap:9,color:'#fff',textDecoration:'none',fontWeight:800,fontSize:22}}><img src="/tuenti_inkorium_logo.svg" alt="Inkorium" style={{width:32,height:32,filter:'brightness(0) invert(1)'}}/><span>inkorium</span></Link>
      <nav style={{display:'flex',height:'100%'}}><HeaderLink to="/feed" label="Inicio" active/><HeaderLink to="/messages" label="Mensajes" badge="3"/><HeaderLink to="/friends" label="Personas"/><HeaderLink to="/events" label="Música" icon={<Music2 size={16}/>}/></nav>
      <div style={{flex:1,padding:'0 22px'}}><input type="search" placeholder="Buscar personas, música, vídeos..." style={{width:'100%',height:36,borderRadius:20,border:'1px solid #003f8b',background:'#064da8',color:'#fff',padding:'0 18px',fontSize:14,outline:'none'}}/></div>
      <div style={{display:'flex',alignItems:'center',gap:5}}><Link to="/notifications" style={{position:'relative',color:'#fff',padding:9}} aria-label="Notificaciones"><Bell size={19}/><span style={{position:'absolute',right:1,top:1,background:'#f43f4f',borderRadius:10,minWidth:16,textAlign:'center',fontSize:10,lineHeight:'16px'}}>5</span></Link><button type="button" style={{color:'#fff',background:'transparent',border:0,padding:9}}><Music2 size={19}/></button><span style={{height:28,width:1,background:'rgba(255,255,255,.25)',margin:'0 5px'}}/><Link to="/profile/$username" params={{username:user?.user_metadata?.username||'me'}} style={{display:'flex',alignItems:'center',gap:7,color:'#fff',textDecoration:'none'}}><img src={avatar} alt="Perfil" style={{width:32,height:32,borderRadius:'50%',objectFit:'cover',border:'2px solid rgba(255,255,255,.5)'}}/><span style={{fontWeight:700,fontSize:14}}>{displayName}</span><ChevronDown size={14}/></Link><button type="button" onClick={handleSignOut} style={{color:'#fff',background:'transparent',border:0,padding:9}}><LogOut size={18}/></button></div>
    </div></header>
    <div style={{width:'100%',maxWidth:1500,margin:'0 auto',padding:'16px 18px 40px',display:'grid',gridTemplateColumns:'280px minmax(0,1fr) 300px',gap:18,alignItems:'start'}}>
      <aside style={{display:'grid',gap:16}}>
        <section style={card}><div style={{display:'flex',gap:12,alignItems:'center'}}><img src={avatar} alt="Perfil" style={{width:82,height:82,borderRadius:10,border:'1px solid #d9e1e8',objectFit:'cover'}}/><div><b style={{fontSize:16}}>{displayName}</b><div style={{marginTop:5,color:'#6d7d90',fontSize:14}}>Más rápido</div><div style={{marginTop:5,color:'#16a34a',fontSize:14}}>● &nbsp;En línea</div><Link to="/profile/$username" params={{username:user?.user_metadata?.username||'me'}} style={{display:'inline-block',marginTop:5,color:'#0755b8',textDecoration:'none',fontSize:13,fontWeight:700}}>Ver mi perfil »</Link></div></div></section>
        <section style={card}><SideNavItem to="/feed" icon={<Home size={19}/>} label="Novedades" active/><SideNavItem to="/feed" icon={<ImageIcon size={19}/>} label="Fotos"/><SideNavItem to="/feed" icon={<Video size={19}/>} label="Vídeos"/><SideNavItem to="/events" icon={<Music2 size={19}/>} label="Música"/><SideNavItem to="/events" icon={<CalendarDays size={19}/>} label="Eventos"/><SideNavItem to="/friends" icon={<Users size={19}/>} label="Grupos"/><SideNavItem to="/friends" icon={<Users size={19}/>} label="Páginas"/><SideNavItem to="/feed" icon={<span>▥</span>} label="Encuestas"/><SideNavItem to="/feed" icon={<span style={{fontSize:20}}>♡</span>} label="Guardados"/><SideNavItem to="/feed" icon={<Settings size={19}/>} label="Configuración"/></section>
        <section style={card}><div style={{display:'flex',justifyContent:'space-between',marginBottom:8}}><b style={{fontSize:11,color:'#617185'}}>AMIGOS CONECTADOS (3)</b><Link to="/friends" style={{fontSize:11,color:'#0755b8',textDecoration:'none'}}>Ver todos »</Link></div>{friends.map(f=><div key={f.name} style={{display:'flex',alignItems:'center',gap:10,padding:'7px 0'}}><img src={`https://i.pravatar.cc/150?img=${f.image}`} alt="" style={{width:42,height:42,borderRadius:'50%',objectFit:'cover'}}/><div><b style={{fontSize:13}}>{f.name}</b><div style={{fontSize:11,color:'#6d7d90'}}>{f.music}</div></div></div>)}</section>
      </aside>
      <main style={{minWidth:0}}>{children}</main>
      <aside style={{display:'grid',gap:16}}><RightCard title="SOLICITUDES" action="Ver todas"><p style={{margin:0,color:'#6d7d90',fontSize:14}}>No tienes solicitudes pendientes.</p></RightCard><RightCard title="EVENTOS PATROCINADOS" action="Ver todos"><div style={{display:'flex',gap:10}}><div style={{width:70,height:60,display:'grid',placeItems:'center',background:'#eef2f6',fontSize:11,color:'#6d7d90'}}>Evento</div><div><b style={{color:'#0755b8',fontSize:14}}>Concierto Indie en Madrid</b><p style={{margin:'5px 0 0',fontSize:12,color:'#6d7d90'}}>Viernes, 24 de Mayo a las 21:00<br/>Sala La Riviera</p><button type="button" style={{marginTop:8,border:'1px solid #4f89cf',borderRadius:16,padding:'5px 10px',background:'#fff',color:'#0755b8',fontWeight:700,fontSize:11}}>Añadir a mi calendario</button></div></div></RightCard><section style={card}><div style={{display:'flex',justifyContent:'space-between'}}><b style={{fontSize:11,color:'#617185'}}>CALENDARIO</b><CalendarDays size={17} color="#6d7d90"/></div><div style={{display:'flex',justifyContent:'space-between',marginTop:18,fontWeight:700}}><span>‹</span><span>Julio 2026</span><span>›</span></div><div style={{marginTop:18,display:'grid',gridTemplateColumns:'repeat(7,1fr)',gap:'12px 2px',textAlign:'center',fontSize:12,color:'#6d7d90'}}>{['Lu','Ma','Mi','Ju','Vi','Sa','Do'].map(d=><b key={d}>{d}</b>)}{['29','30','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','1','2'].map((d,i)=><span key={`${d}-${i}`} style={i===32?{width:28,height:28,border:'1px solid #0755b8',borderRadius:'50%',display:'grid',placeItems:'center',margin:'-7px auto 0',color:'#0755b8',fontWeight:700}:{}}>{d}</span>)}</div></section></aside>
    </div>
  </div>;
}
function HeaderLink({to,label,active=false,badge,icon}:{to:'/feed'|'/messages'|'/friends'|'/events';label:string;active?:boolean;badge?:string;icon?:React.ReactNode}){return <Link to={to} style={{position:'relative',display:'flex',alignItems:'center',gap:6,padding:'0 15px',color:'#fff',textDecoration:'none',fontSize:14,fontWeight:700,background:active?'#06458f':'transparent',borderBottom:active?'4px solid #fff':'4px solid transparent'}}>{icon}{label}{badge&&<span style={{position:'absolute',top:2,right:3,background:'#f43f4f',borderRadius:10,padding:'0 5px',fontSize:10,lineHeight:'17px'}}>{badge}</span>}</Link>}
function SideNavItem({to,icon,label,active=false}:{to:'/feed'|'/events'|'/friends';icon:React.ReactNode;label:string;active?:boolean}){return <Link to={to} style={{display:'flex',alignItems:'center',gap:12,padding:'10px 12px',color:active?'#0755b8':'#334155',textDecoration:'none',background:active?'#edf3fa':'transparent',fontWeight:active?800:500,fontSize:14,borderRadius:4}}>{icon}<span>{label}</span></Link>}
function RightCard({title,action,children}:{title:string;action:string;children:React.ReactNode}){return <section style={card}><div style={{display:'flex',justifyContent:'space-between',borderBottom:'1px solid #edf0f3',paddingBottom:11,marginBottom:13}}><b style={{fontSize:11,color:'#617185'}}>{title}</b><button type="button" style={{border:0,background:'transparent',color:'#0755b8',fontSize:11,fontWeight:700}}>{action}</button></div>{children}</section>}
